# Generated by Django 5.2.8 on 2025-12-23 08:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('bed_number', models.CharField(help_text="Bed number/identifier (e.g., 'A-101', 'ICU-05')", max_length=50)),
                ('bed_type', models.CharField(choices=[('general', 'General Bed'), ('icu', 'ICU Bed'), ('ventilator', 'Ventilator Bed'), ('private', 'Private Bed'), ('semi_private', 'Semi-Private Bed'), ('deluxe', 'Deluxe Bed'), ('cabin', 'Cabin'), ('other', 'Other')], default='general', max_length=20)),
                ('daily_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Daily charge for this bed', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_occupied', models.BooleanField(default=False, help_text='Whether bed is currently occupied')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('has_oxygen', models.BooleanField(default=False)),
                ('has_ventilator', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IPD Bed',
                'verbose_name_plural': 'IPD Beds',
                'db_table': 'ipd_beds',
                'ordering': ['ward', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('admission_id', models.CharField(help_text='Unique admission identifier (e.g., IPD/20231223/001)', max_length=50, unique=True)),
                ('doctor_id', models.UUIDField(db_index=True, help_text='SuperAdmin User ID of attending doctor')),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of admission')),
                ('reason', models.TextField(help_text='Reason for admission')),
                ('provisional_diagnosis', models.TextField(blank=True, help_text='Initial diagnosis at admission')),
                ('final_diagnosis', models.TextField(blank=True, help_text='Final diagnosis at discharge')),
                ('discharge_date', models.DateTimeField(blank=True, help_text='Date and time of discharge', null=True)),
                ('discharge_summary', models.TextField(blank=True, help_text='Discharge summary and instructions')),
                ('discharge_type', models.CharField(blank=True, help_text="Type of discharge (e.g., 'Normal', 'Against Medical Advice')", max_length=100)),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('transferred', 'Transferred'), ('absconded', 'Absconded'), ('referred', 'Referred'), ('death', 'Death')], default='admitted', max_length=20)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, help_text='User who created this admission record', null=True)),
                ('discharged_by_user_id', models.UUIDField(blank=True, db_index=True, help_text='User who discharged the patient', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_admissions', to='patients.patientprofile')),
                ('bed', models.ForeignKey(blank=True, help_text='Current bed assignment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='ipd.bed')),
            ],
            options={
                'verbose_name': 'IPD Admission',
                'verbose_name_plural': 'IPD Admissions',
                'db_table': 'ipd_admissions',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='IPDBilling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('bill_number', models.CharField(blank=True, help_text='Unique bill identifier (e.g., IPD-BILL/20231223/001)', max_length=50, unique=True)),
                ('bill_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Bill generation date')),
                ('doctor_id', models.UUIDField(blank=True, db_index=True, help_text='Attending doctor ID', null=True)),
                ('diagnosis', models.TextField(blank=True, help_text='Diagnosis for this bill')),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount (sum of items)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount (calculated or manual)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to be paid (total - discount)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('insurance', 'Insurance'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', help_text='Mode of payment', max_length=20)),
                ('payment_details', models.JSONField(blank=True, default=dict, help_text='Payment transaction details (JSON)')),
                ('received_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount received from patient', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance due (payable - received)', max_digits=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('billed_by_id', models.UUIDField(blank=True, db_index=True, help_text='User who created this bill', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(help_text='Admission this bill belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='ipd_bills', to='ipd.admission')),
            ],
            options={
                'verbose_name': 'IPD Bill',
                'verbose_name_plural': 'IPD Bills',
                'db_table': 'ipd_billings',
                'ordering': ['-bill_date'],
            },
        ),
        migrations.CreateModel(
            name='IPDBillItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('item_name', models.CharField(help_text='Description of the item/service', max_length=200)),
                ('source', models.CharField(choices=[('Bed', 'Bed Charges'), ('Pharmacy', 'Pharmacy'), ('Lab', 'Laboratory'), ('Radiology', 'Radiology'), ('Consultation', 'Consultation'), ('Procedure', 'Procedure'), ('Surgery', 'Surgery'), ('Therapy', 'Therapy'), ('Package', 'Package'), ('Other', 'Other')], default='Other', help_text='Source/category of the charge', max_length=20)),
                ('quantity', models.IntegerField(default=1, help_text='Quantity (e.g., days for bed, units for medicine)', validators=[django.core.validators.MinValueValidator(1)])),
                ('system_calculated_price', models.DecimalField(decimal_places=2, help_text='System-calculated price from master data', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Actual unit price (can be manually overridden)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price (quantity × unit_price)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_price_overridden', models.BooleanField(default=False, help_text='Flag indicating if price was manually changed from system default')),
                ('origin_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the source order/admission', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(help_text='IPD bill this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ipd.ipdbilling')),
                ('origin_content_type', models.ForeignKey(blank=True, help_text='Type of source order/admission (DiagnosticOrder, MedicineOrder, Admission, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'IPD Bill Item',
                'verbose_name_plural': 'IPD Bill Items',
                'db_table': 'ipd_bill_items',
                'ordering': ['bill', 'source', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('name', models.CharField(help_text="Ward name (e.g., 'General Ward A', 'ICU Floor 3')", max_length=200)),
                ('type', models.CharField(choices=[('general', 'General Ward'), ('icu', 'ICU'), ('private', 'Private'), ('semi_private', 'Semi-Private'), ('deluxe', 'Deluxe'), ('nicu', 'NICU'), ('picu', 'PICU'), ('emergency', 'Emergency'), ('maternity', 'Maternity'), ('pediatric', 'Pediatric'), ('surgical', 'Surgical'), ('other', 'Other')], default='general', max_length=20)),
                ('floor', models.CharField(blank=True, help_text="Floor/location (e.g., 'Ground Floor', '3rd Floor')", max_length=50)),
                ('total_beds', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IPD Ward',
                'verbose_name_plural': 'IPD Wards',
                'db_table': 'ipd_wards',
                'ordering': ['floor', 'name'],
                'indexes': [models.Index(fields=['tenant_id'], name='ipd_wards_tenant__155996_idx'), models.Index(fields=['tenant_id', 'is_active'], name='ipd_wards_tenant__060970_idx'), models.Index(fields=['type'], name='ipd_wards_type_97c4cc_idx')],
                'unique_together': {('tenant_id', 'name')},
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='ipd.ward'),
        ),
        migrations.AddField(
            model_name='admission',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='ipd.ward'),
        ),
        migrations.CreateModel(
            name='BedTransfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of transfer')),
                ('reason', models.TextField(help_text='Reason for bed transfer')),
                ('performed_by_user_id', models.UUIDField(blank=True, db_index=True, help_text='User who performed the transfer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_transfers', to='ipd.admission')),
                ('from_bed', models.ForeignKey(help_text='Original bed', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='ipd.bed')),
                ('to_bed', models.ForeignKey(help_text='New bed', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='ipd.bed')),
            ],
            options={
                'verbose_name': 'IPD Bed Transfer',
                'verbose_name_plural': 'IPD Bed Transfers',
                'db_table': 'ipd_bed_transfers',
                'ordering': ['-transfer_date'],
                'indexes': [models.Index(fields=['tenant_id'], name='ipd_bed_tra_tenant__5574a0_idx'), models.Index(fields=['admission', '-transfer_date'], name='ipd_bed_tra_admissi_514928_idx'), models.Index(fields=['transfer_date'], name='ipd_bed_tra_transfe_3c90ef_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ipdbilling',
            index=models.Index(fields=['tenant_id'], name='ipd_billing_tenant__5aed33_idx'),
        ),
        migrations.AddIndex(
            model_name='ipdbilling',
            index=models.Index(fields=['tenant_id', 'payment_status'], name='ipd_billing_tenant__4ff454_idx'),
        ),
        migrations.AddIndex(
            model_name='ipdbilling',
            index=models.Index(fields=['admission', 'bill_date'], name='ipd_billing_admissi_477808_idx'),
        ),
        migrations.AddIndex(
            model_name='ipdbilling',
            index=models.Index(fields=['bill_number'], name='ipd_bill_number_idx'),
        ),
        migrations.AddIndex(
            model_name='ipdbilling',
            index=models.Index(fields=['payment_status'], name='ipd_payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ipdbillitem',
            index=models.Index(fields=['tenant_id'], name='ipd_bill_it_tenant__1524ad_idx'),
        ),
        migrations.AddIndex(
            model_name='ipdbillitem',
            index=models.Index(fields=['bill', 'source'], name='ipd_bill_it_bill_id_05f1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='ipdbillitem',
            index=models.Index(fields=['origin_content_type', 'origin_object_id'], name='ipd_bill_it_origin__02f5d1_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['tenant_id'], name='ipd_beds_tenant__7c95dd_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['tenant_id', 'is_occupied'], name='ipd_beds_tenant__c237f6_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['tenant_id', 'status'], name='ipd_beds_tenant__fb2daf_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['ward', 'is_occupied'], name='ipd_beds_ward_id_d03b71_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['is_active'], name='ipd_beds_is_acti_9b2163_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('tenant_id', 'ward', 'bed_number')},
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['tenant_id'], name='ipd_admissi_tenant__761f81_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['tenant_id', 'status'], name='ipd_admissi_tenant__864081_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['tenant_id', 'admission_date'], name='ipd_admissi_tenant__4eef5d_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['admission_id'], name='ipd_admission_id_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['patient', 'admission_date'], name='ipd_patient_date_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['doctor_id', 'admission_date'], name='ipd_doctor_date_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['status'], name='ipd_status_idx'),
        ),
    ]
