# Generated by Django 5.2.8 on 2025-12-21 19:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ipd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdbillitem',
            name='is_price_overridden',
            field=models.BooleanField(default=False, help_text='Flag indicating if price was manually changed from system default'),
        ),
        migrations.AddField(
            model_name='ipdbillitem',
            name='origin_content_type',
            field=models.ForeignKey(blank=True, help_text='Type of source order/admission (DiagnosticOrder, MedicineOrder, Admission, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='ipdbillitem',
            name='origin_object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the source order/admission', null=True),
        ),
        migrations.AddField(
            model_name='ipdbillitem',
            name='system_calculated_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='System-calculated price from master data', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ipdbillitem',
            name='source',
            field=models.CharField(choices=[('Bed', 'Bed Charges'), ('Pharmacy', 'Pharmacy'), ('Lab', 'Laboratory'), ('Radiology', 'Radiology'), ('Consultation', 'Consultation'), ('Procedure', 'Procedure'), ('Surgery', 'Surgery'), ('Therapy', 'Therapy'), ('Package', 'Package'), ('Other', 'Other')], default='Other', help_text='Source/category of the charge', max_length=20),
        ),
        migrations.AlterField(
            model_name='ipdbillitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Actual unit price (can be manually overridden)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='ipdbillitem',
            index=models.Index(fields=['origin_content_type', 'origin_object_id'], name='ipd_bill_it_origin__02f5d1_idx'),
        ),
    ]
