# Generated by Django 5.2.9 on 2026-06-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0002_admission_mediclaim_claim'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='admission',
            new_name='ipd_admissi_tenant__4fded9_idx',
            old_name='ipd_admissi_tenant__690689_idx',
        ),
        migrations.RenameIndex(
            model_name='admission',
            new_name='ipd_admissi_tenant__ea87ed_idx',
            old_name='ipd_admissi_tenant__7670cf_idx',
        ),
    ]
