# Generated by Django 5.2.9 on 2026-06-28 22:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0003_rename_ipd_admissi_tenant__690689_idx_ipd_admissi_tenant__4fded9_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipdbillitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='ipdbillitem',
            name='ipd_bill_it_bill_id_05f1a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='ipdbillitem',
            name='ipd_bill_it_origin__02f5d1_idx',
        ),
        migrations.RemoveField(
            model_name='ipdbillitem',
            name='is_price_overridden',
        ),
        migrations.RemoveField(
            model_name='ipdbillitem',
            name='origin_content_type',
        ),
        migrations.RemoveField(
            model_name='ipdbillitem',
            name='origin_object_id',
        ),
        migrations.AlterField(
            model_name='ipdbillitem',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ipdbillitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Total price for this item', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='ipdbillitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Actual unit price charged (may differ from system price)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='ipdbillitem',
            index=models.Index(fields=['tenant_id', 'bill'], name='ipd_bill_it_tenant__a27aa5_idx'),
        ),
    ]
