# Generated by Django 5.2.9 on 2026-08-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0008_ipdbillitem_service_source'),
        ('patients', '0002_patient_registration_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('emergency', 'Emergency'), ('transfer', 'Transfer'), ('readmission', 'Readmission'), ('daycare', 'Daycare')], default='regular', help_text='Type of admission', max_length=20),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['tenant_id', 'admission_type'], name='ipd_admissi_tenant__bb0cf9_idx'),
        ),
    ]
