# Generated by Django 5.2.9 on 2026-08-07 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0009_alter_admission_admission_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargePacket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'AI Generated'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('narrative', models.TextField(blank=True, default='')),
                ('sections_snapshot', models.JSONField(blank=True, default=list)),
                ('source_record_ids', models.JSONField(blank=True, default=list)),
                ('ai_model', models.CharField(blank=True, default='', max_length=100)),
                ('generation_count', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by_user_id', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_user_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_packet', to='ipd.admission')),
            ],
            options={
                'db_table': 'ipd_discharge_packets',
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='ipd_dischar_tenant__a74558_idx')],
            },
        ),
    ]
