# Generated by Django 5.2.9 on 2026-08-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0010_dischargepacket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdbilling',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('online', 'Online'), ('insurance', 'Insurance'), ('cheque', 'Cheque'), ('multiple', 'Multiple Modes'), ('other', 'Other')], default='cash', help_text='Mode of payment', max_length=20),
        ),
    ]
