# Generated by Django 5.2.9 on 2026-08-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0011_alter_ipdbilling_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdbilling',
            name='bill_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('mediclaim', 'Mediclaim')], db_index=True, default='regular', help_text='Regular itemized bill vs a Mediclaim claim bill for the TPA/insurer.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='ipdbilling',
            index=models.Index(fields=['tenant_id', 'bill_type'], name='ipd_billing_tenant__ff68b8_idx'),
        ),
    ]
