# Generated by Django 5.2.9 on 2026-08-19 07:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0012_ipdbilling_bill_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='advance_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of advance BillPayment.applied_amount for this admission (already moved onto a bill).', max_digits=12),
        ),
        migrations.AddField(
            model_name='admission',
            name='advance_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='total_advance_paid - advance_applied.', max_digits=12),
        ),
        migrations.AddField(
            model_name='admission',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='total_charges - total_received.', max_digits=12),
        ),
        migrations.AddField(
            model_name='admission',
            name='total_advance_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Sum of BillPayment.amount for bill_type='advance' rows on this admission.", max_digits=12),
        ),
        migrations.AddField(
            model_name='admission',
            name='total_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Sum of payable_amount across this admission's non-mediclaim IPDBilling rows.", max_digits=12),
        ),
        migrations.AddField(
            model_name='admission',
            name='total_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of received_amount across non-mediclaim bills, plus advance_applied.', max_digits=12),
        ),
        migrations.AddField(
            model_name='ipdbilling',
            name='paid_transition_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp of this bill's most recent unpaid/partial -> paid transition.", null=True),
        ),
        migrations.AlterField(
            model_name='ipdbilling',
            name='bill_number',
            field=models.CharField(blank=True, help_text='Unique (per tenant) bill identifier (e.g., IPD-BILL/20231223/001)', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='ipdbilling',
            unique_together={('tenant_id', 'bill_number')},
        ),
        migrations.CreateModel(
            name='IPDBillingSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('bill_date', models.DateField(db_index=True)),
                ('prefix', models.CharField(default='IPD-BILL', max_length=30)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'ipd_bill_sequences',
                'unique_together': {('tenant_id', 'bill_date', 'prefix')},
            },
        ),
    ]
