# Generated by Django 5.2.9 on 2026-08-19 15:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0013_admission_advance_applied_admission_advance_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='total_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Sum of received_amount across non-mediclaim bills. Already includes any applied-advance money (apply_advance writes it directly onto a bill's received_amount), so this is NOT bills_received + advance_applied.", max_digits=12),
        ),
    ]
