# Generated by Django 5.2.9 on 2026-08-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0014_alter_admission_total_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdbillitem',
            name='is_quantity_overridden',
            field=models.BooleanField(default=False, help_text='Flag indicating quantity was manually corrected by staff (e.g. bed days). System recalculation (IPDBilling.add_bed_charges) skips items with this set, unless explicitly forced, so a manual correction is never silently overwritten by an unrelated edit.'),
        ),
    ]
