# Generated by Django 5.0.14 on 2025-11-21 15:31

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('service', 'Service Fee'), ('delivery', 'Delivery Fee'), ('tax', 'Tax'), ('consultation', 'Consultation Fee'), ('misc', 'Miscellaneous Fee')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_percentage', models.BooleanField(default=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'Fee Type',
                'verbose_name_plural': 'Fee Types',
                'db_table': 'fee_types',
                'indexes': [models.Index(fields=['tenant_id'], name='fee_types_tenant__24b710_idx'), models.Index(fields=['tenant_id', 'category'], name='fee_types_tenant__467c06_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('user_id', models.UUIDField(blank=True, help_text='User who created this order', null=True)),
                ('services_type', models.CharField(choices=[('diagnostic', 'Diagnostic Services'), ('nursing_care', 'Nursing Care'), ('home_healthcare', 'Home Healthcare'), ('consultation', 'Doctor Consultation'), ('laboratory', 'Laboratory Tests'), ('pharmacy', 'Pharmacy')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('net_banking', 'Net Banking'), ('online', 'Online Payment'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=20, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, help_text='Additional order notes or instructions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='patients.patientprofile')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_fee_details', to='orders.feetype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_fee_details', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Fee',
                'verbose_name_plural': 'Order Fees',
                'db_table': 'order_fees',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='fees',
            field=models.ManyToManyField(related_name='orders', through='orders.OrderFee', to='orders.feetype'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='orderfee',
            index=models.Index(fields=['tenant_id'], name='order_fees_tenant__1cf63c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderfee',
            index=models.Index(fields=['tenant_id', 'order'], name='order_fees_tenant__92dedd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderfee',
            unique_together={('order', 'fee_type')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant_id'], name='orders_tenant__58de9e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant_id', 'status'], name='orders_tenant__ed6a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant_id', 'created_at'], name='orders_tenant__5b564e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['patient', 'status'], name='orders_patient_cc50b0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_created_77e2b9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['tenant_id'], name='order_items_tenant__23d97e_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['tenant_id', 'order'], name='order_items_tenant__c0e620_idx'),
        ),
    ]
