# Generated by Django 5.2.9 on 2025-12-26 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('orders', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this config belongs to', unique=True)),
                ('razorpay_key_id', models.CharField(help_text='Razorpay Key ID from dashboard', max_length=255)),
                ('razorpay_key_secret', models.CharField(help_text='Razorpay Key Secret (encrypted storage recommended)', max_length=255)),
                ('razorpay_webhook_secret', models.CharField(help_text='Razorpay Webhook Secret for signature verification', max_length=255)),
                ('is_test_mode', models.BooleanField(default=True, help_text='Use test mode credentials')),
                ('is_active', models.BooleanField(default=True, help_text='Enable Razorpay payments for this tenant')),
                ('auto_capture', models.BooleanField(default=True, help_text='Automatically capture payments (vs manual capture)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Razorpay Configuration',
                'verbose_name_plural': 'Razorpay Configurations',
                'db_table': 'razorpay_configs',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text='Associated appointment for consultation orders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by_user_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='SuperAdmin User ID who cancelled this order', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by_user_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='SuperAdmin User ID who created this order', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_failed_reason',
            field=models.TextField(blank=True, help_text='Reason if payment failed', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_verified',
            field=models.BooleanField(default=False, help_text='Whether Razorpay payment signature was verified'),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, help_text='Razorpay order ID', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, db_index=True, help_text='Razorpay payment ID after successful payment', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(blank=True, help_text='Razorpay signature for verification', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('net_banking', 'Net Banking'), ('online', 'Online Payment'), ('razorpay', 'Razorpay'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['razorpay_order_id'], name='orders_razorpa_509fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['razorpay_payment_id'], name='orders_razorpa_598de9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant_id', 'payment_verified'], name='orders_tenant__db9782_idx'),
        ),
    ]
