# Generated by Django 5.2.9 on 2026-07-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_hospital_theme_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='inventory_config',
            field=models.JSONField(blank=True, default=dict, help_text='Tenant-wide inventory defaults.'),
        ),
    ]
