# Generated by Django 5.2.9 on 2026-08-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_hospital_inventory_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='daycare_prefix',
            field=models.CharField(default='DAYCARE', help_text='Prefix used for Daycare admission, billing, and discharge documents.', max_length=24),
        ),
    ]
