# Generated by Django 5.2.9 on 2026-08-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_hospital_daycare_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='clinical_summary_system_prompt',
            field=models.TextField(blank=True, default='', help_text='Tenant-configurable system prompt for the AI-generated IPD discharge clinical summary. Empty uses the built-in default.'),
        ),
    ]
