# Generated by Django 5.2.9 on 2026-08-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_hospital_clinical_summary_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='ipd_billing_mode',
            field=models.CharField(choices=[('multiple', 'Multiple Bills'), ('single_accumulated', 'Single Accumulated Bill')], default='multiple', help_text='Whether IPD admissions may have multiple bills, or a single accumulated bill.', max_length=20),
        ),
    ]
