from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import DoctorProfileViewSet, SpecialtyViewSet

# Create router and register viewsets
router = DefaultRouter()
router.register(r'profiles', DoctorProfileViewSet, basename='doctor-profile')
router.register(r'specialties', SpecialtyViewSet, basename='specialty')

urlpatterns = [
    # Explicit URL for creating doctor with user (also auto-generated by router)
    # POST /api/doctors/profiles/create_with_user/
    path('profiles/create_with_user/',
         DoctorProfileViewSet.as_view({'post': 'create_with_user'}),
         name='doctor-profile-create-with-user'),

    # Include all router URLs
    path('', include(router.urls)),
]