# Generated by Django 5.2.9 on 2025-12-17 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNoteResponseTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenancy')),
                ('name', models.CharField(help_text="User-defined template name (e.g., 'Standard Follow-up', 'Initial Diabetes Consultation')", max_length=200)),
                ('description', models.TextField(blank=True, help_text="What this response template is for (e.g., 'Standard pattern for diabetes follow-ups')")),
                ('template_field_values', models.JSONField(default=dict, help_text='Stores cloned field responses for quick reuse. Format: {field_name: {label, type, value}}')),
                ('is_active', models.BooleanField(default=True, help_text='Can be archived/deactivated')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this template has been used')),
                ('created_by_id', models.UUIDField(db_index=True, help_text='User ID of doctor who created this reusable template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinical Note Response Template',
                'verbose_name_plural': 'Clinical Note Response Templates',
                'db_table': 'clinical_note_response_templates',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='clinicalnotetemplateresponse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clinicalnotetemplatefieldresponse',
            name='canvas_thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated thumbnail of the canvas.', null=True, upload_to='canvas_thumbnails/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='clinicalnotetemplatefieldresponse',
            name='canvas_version_history',
            field=models.JSONField(blank=True, default=list, help_text='History of previous canvas JSON states.', null=True),
        ),
        migrations.AddField(
            model_name='clinicalnotetemplatefieldresponse',
            name='full_canvas_json',
            field=models.JSONField(blank=True, default=dict, help_text='Full Excalidraw JSON data for the canvas.', null=True),
        ),
        migrations.AddField(
            model_name='clinicalnotetemplateresponse',
            name='canvas_data',
            field=models.FileField(blank=True, help_text='Canvas image if doctor used stylus instead of structured input', null=True, upload_to='clinical_notes/canvas/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='clinicalnotetemplateresponse',
            name='doctor_switched_reason',
            field=models.TextField(blank=True, help_text='Reason for doctor change (absence, handover, specialty consultation, etc.)'),
        ),
        migrations.AddField(
            model_name='clinicalnotetemplateresponse',
            name='is_reviewed',
            field=models.BooleanField(default=False, help_text='Has this response been reviewed/approved by supervising doctor'),
        ),
        migrations.AddField(
            model_name='clinicalnotetemplateresponse',
            name='original_assigned_doctor_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='User ID of originally assigned doctor (tracks who was first assigned)', null=True),
        ),
        migrations.AddField(
            model_name='clinicalnotetemplateresponse',
            name='response_sequence',
            field=models.IntegerField(default=1, help_text='Sequence number for multiple responses (1st, 2nd, 3rd fill of same template on same visit)'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicalnotetemplateresponse',
            unique_together={('visit', 'template', 'response_sequence')},
        ),
        migrations.AddIndex(
            model_name='clinicalnotetemplateresponse',
            index=models.Index(fields=['visit', 'template', 'response_sequence'], name='clinical_no_visit_i_d8dc28_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnotetemplateresponse',
            index=models.Index(fields=['original_assigned_doctor_id'], name='clinical_no_origina_024f03_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnotetemplateresponse',
            index=models.Index(fields=['is_reviewed'], name='clinical_no_is_revi_f5692b_idx'),
        ),
        migrations.AddField(
            model_name='clinicalnoteresponsetemplate',
            name='source_response',
            field=models.ForeignKey(blank=True, help_text='Original response this template was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_templates', to='opd.clinicalnotetemplateresponse'),
        ),
        migrations.AddIndex(
            model_name='clinicalnoteresponsetemplate',
            index=models.Index(fields=['tenant_id'], name='clinical_no_tenant__e6d601_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnoteresponsetemplate',
            index=models.Index(fields=['tenant_id', 'is_active'], name='clinical_no_tenant__05a27a_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnoteresponsetemplate',
            index=models.Index(fields=['created_by_id'], name='clinical_no_created_2413c8_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnoteresponsetemplate',
            index=models.Index(fields=['-usage_count'], name='clinical_no_usage_c_b6e6ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicalnoteresponsetemplate',
            unique_together={('tenant_id', 'name', 'created_by_id')},
        ),
    ]
