# Generated by Django 5.2.9 on 2025-12-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdbill',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('razorpay', 'Razorpay'), ('multiple', 'Multiple Modes')], default='cash', max_length=20),
        ),
    ]
