# Generated by Django 5.2.9 on 2025-12-20 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('opd', '0002_clinicalnoteresponsetemplate_and_more'),
    ]

    operations = [
        # Step 1: Add nullable content_type and object_id fields
        migrations.AddField(
            model_name='clinicalnotetemplateresponse',
            name='content_type',
            field=models.ForeignKey(
                null=True,
                blank=True,
                help_text='Type of encounter (OPD Visit or IPD Admission)',
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype'
            ),
        ),
        migrations.AddField(
            model_name='clinicalnotetemplateresponse',
            name='object_id',
            field=models.PositiveIntegerField(
                null=True,
                blank=True,
                help_text='ID of the encounter record'
            ),
        ),
    ]
