# Generated by Django 5.2.9 on 2025-12-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0002_alter_opdbill_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalnotetemplatefieldresponse',
            name='value_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
