# Generated by Django 5.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0003_alter_clinicalnotetemplatefieldresponse_value_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdbill',
            name='charge_type',
            field=models.CharField(
                choices=[
                    ('first_visit', 'First Visit'),
                    ('revisit', 'Revisit'),
                    ('follow_up', 'Follow-up'),
                    ('emergency', 'Emergency'),
                ],
                default='first_visit',
                max_length=20,
            ),
        ),
    ]
