# Generated by Django 5.2.9 on 2025-12-20 06:10

from django.db import migrations


def migrate_visit_to_encounter(apps, schema_editor):
    """
    Migrate existing visit foreign keys to content_type + object_id.

    This converts the old visit ForeignKey to the new GenericForeignKey system.
    """
    ClinicalNoteTemplateResponse = apps.get_model('opd', 'ClinicalNoteTemplateResponse')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Get the ContentType for Visit model
    try:
        visit_content_type = ContentType.objects.get(app_label='opd', model='visit')
    except ContentType.DoesNotExist:
        # If ContentType doesn't exist, create it
        visit_content_type = ContentType.objects.create(app_label='opd', model='visit')

    # Update all existing ClinicalNoteTemplateResponse records
    responses = ClinicalNoteTemplateResponse.objects.all()

    for response in responses:
        if response.visit_id:  # If there's a visit associated
            response.content_type = visit_content_type
            response.object_id = response.visit_id
            response.save(update_fields=['content_type', 'object_id'])

    print(f"Migrated {responses.count()} ClinicalNoteTemplateResponse records to new encounter system")


def reverse_migrate_encounter_to_visit(apps, schema_editor):
    """
    Reverse migration: This is a no-op since we're keeping the visit field
    until the next migration removes it.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('opd', '0003_add_encounter_fields'),
    ]

    operations = [
        migrations.RunPython(
            migrate_visit_to_encounter,
            reverse_migrate_encounter_to_visit
        ),
    ]
