# Generated by Django 5.2.9 on 2025-12-20 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('opd', '0004_migrate_visit_to_encounter'),
    ]

    operations = [
        # Step 1: Remove old indexes and constraints that reference visit
        migrations.RemoveIndex(
            model_name='clinicalnotetemplateresponse',
            name='clinical_no_visit_i_2e1f64_idx',
        ),
        migrations.RemoveIndex(
            model_name='clinicalnotetemplateresponse',
            name='clinical_no_visit_i_d8dc28_idx',
        ),
        migrations.AlterUniqueTogether(
            name='clinicalnotetemplateresponse',
            unique_together=set(),
        ),

        # Step 2: Make content_type and object_id non-nullable
        migrations.AlterField(
            model_name='clinicalnotetemplateresponse',
            name='content_type',
            field=models.ForeignKey(
                help_text='Type of encounter (OPD Visit or IPD Admission)',
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype'
            ),
        ),
        migrations.AlterField(
            model_name='clinicalnotetemplateresponse',
            name='object_id',
            field=models.PositiveIntegerField(
                help_text='ID of the encounter record'
            ),
        ),

        # Step 3: Add new indexes for encounter fields
        migrations.AddIndex(
            model_name='clinicalnotetemplateresponse',
            index=models.Index(
                fields=['content_type', 'object_id'],
                name='clinical_no_content_bdb42b_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='clinicalnotetemplateresponse',
            index=models.Index(
                fields=['content_type', 'object_id', 'template', 'response_sequence'],
                name='clinical_no_content_fc411c_idx'
            ),
        ),

        # Step 4: Add unique constraint for encounter + template + sequence
        migrations.AddConstraint(
            model_name='clinicalnotetemplateresponse',
            constraint=models.UniqueConstraint(
                fields=('content_type', 'object_id', 'template', 'response_sequence'),
                name='unique_response_per_encounter_template'
            ),
        ),

        # Step 5: Remove the old visit field
        migrations.RemoveField(
            model_name='clinicalnotetemplateresponse',
            name='visit',
        ),
    ]
