# Generated by Django 5.2.8 on 2025-12-21 18:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('opd', '0005_finalize_encounter_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPDBillItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('item_name', models.CharField(help_text='Description of the item/service', max_length=200)),
                ('source', models.CharField(choices=[('Consultation', 'Consultation'), ('Pharmacy', 'Pharmacy'), ('Lab', 'Laboratory'), ('Radiology', 'Radiology'), ('Procedure', 'Procedure'), ('Package', 'Package'), ('Therapy', 'Therapy'), ('Other', 'Other')], default='Other', help_text='Source/category of the charge', max_length=20)),
                ('quantity', models.IntegerField(default=1, help_text='Quantity (e.g., units for medicine, sessions for procedures)', validators=[django.core.validators.MinValueValidator(1)])),
                ('system_calculated_price', models.DecimalField(decimal_places=2, help_text='System-calculated price from master data', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Actual unit price (can be manually overridden)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price (quantity × unit_price)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_price_overridden', models.BooleanField(default=False, help_text='Flag indicating if price was manually changed from system default')),
                ('origin_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the source order', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_content_type', models.ForeignKey(blank=True, help_text='Type of source order (DiagnosticOrder, MedicineOrder, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='opd.visit')),
            ],
            options={
                'verbose_name': 'OPD Bill Item',
                'verbose_name_plural': 'OPD Bill Items',
                'db_table': 'opd_bill_items',
                'ordering': ['visit', 'source', 'id'],
                'indexes': [models.Index(fields=['tenant_id'], name='opd_bill_it_tenant__199569_idx'), models.Index(fields=['visit', 'source'], name='opd_bill_it_visit_i_62b072_idx'), models.Index(fields=['origin_content_type', 'origin_object_id'], name='opd_bill_it_origin__44074e_idx')],
            },
        ),
    ]
