# Generated by Django 5.2.9 on 2026-05-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0005_alter_visit_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdbill',
            name='bill_number',
            field=models.CharField(help_text='Unique bill identifier (e.g., OPD-BILL/20231223/001)', max_length=50),
        ),
        migrations.AlterField(
            model_name='proceduremaster',
            name='code',
            field=models.CharField(help_text='Unique procedure code per tenant', max_length=50),
        ),
        migrations.AlterField(
            model_name='procedurepackage',
            name='code',
            field=models.CharField(help_text='Unique package code per tenant', max_length=50),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_number',
            field=models.CharField(help_text='Unique visit identifier (e.g., OPD/20231223/001)', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='opdbill',
            unique_together={('tenant_id', 'bill_number')},
        ),
        migrations.AlterUniqueTogether(
            name='proceduremaster',
            unique_together={('tenant_id', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='procedurepackage',
            unique_together={('tenant_id', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together={('tenant_id', 'visit_number')},
        ),
    ]
