# Generated by Django 5.2.8 on 2025-12-21 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('opd', '0006_update_order_billing_bridge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedurebill',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='procedurebill',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='procedurebillitem',
            name='procedure_bill',
        ),
        migrations.RemoveField(
            model_name='procedurebillitem',
            name='procedure',
        ),
        migrations.AlterModelOptions(
            name='opdbillitem',
            options={'ordering': ['bill', 'source', 'id'], 'verbose_name': 'OPD Bill Item', 'verbose_name_plural': 'OPD Bill Items'},
        ),
        migrations.RemoveIndex(
            model_name='opdbillitem',
            name='opd_bill_it_visit_i_62b072_idx',
        ),
        migrations.RemoveField(
            model_name='opdbillitem',
            name='visit',
        ),
        migrations.AddField(
            model_name='opdbillitem',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='opd.opdbill'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='opdbillitem',
            index=models.Index(fields=['bill', 'source'], name='opd_bill_it_bill_id_cd28c1_idx'),
        ),
        migrations.DeleteModel(
            name='ProcedureBill',
        ),
        migrations.DeleteModel(
            name='ProcedureBillItem',
        ),
    ]
