# Generated by Django 5.2.9 on 2026-06-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0006_fix_per_tenant_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='follow_up_date',
            field=models.DateField(blank=True, db_index=True, help_text='Scheduled follow-up date (migrated from ClinicalNote.next_followup_date)', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='follow_up_notes',
            field=models.TextField(blank=True, help_text='Notes or instructions for the follow-up visit', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='follow_up_required',
            field=models.BooleanField(default=False, help_text='Whether a follow-up visit is required'),
        ),
    ]
