# Generated by Django 5.2.8 on 2025-12-22 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0007_remove_procedurebill_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdbill',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opd_bills', to='opd.visit'),
        ),
    ]
