# Generated by Django 5.2.9 on 2026-06-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0008_visit_priority_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('new', 'New Visit'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency'), ('referral', 'Referral')], default='new', max_length=20),
        ),
    ]
