# Generated by Django 5.2.9 on 2026-08-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0012_alter_opdbill_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdbillitem',
            name='source',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Pharmacy', 'Pharmacy'), ('Lab', 'Laboratory'), ('Radiology', 'Radiology'), ('Procedure', 'Procedure'), ('Package', 'Package'), ('Service', 'Service'), ('Therapy', 'Therapy'), ('Other', 'Other')], default='Other', help_text='Source/category of the charge', max_length=20),
        ),
    ]
