# Generated by Django 5.2.9 on 2026-08-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0013_alter_opdbillitem_source_add_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_mediclaim_available',
            field=models.BooleanField(default=False, help_text='Whether this service is claimable under Mediclaim/TPA insurance'),
        ),
    ]
