# Generated by Django 5.2.9 on 2026-08-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0014_service_add_mediclaim_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPDBillSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('bill_date', models.DateField(db_index=True)),
                ('prefix', models.CharField(default='OPD-BILL', max_length=30)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'opd_bill_sequences',
                'unique_together': {('tenant_id', 'bill_date', 'prefix')},
            },
        ),
    ]
