# Generated by Django 5.2.9 on 2026-08-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0015_add_opd_bill_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdbill',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('online', 'Online'), ('razorpay', 'Razorpay'), ('multiple', 'Multiple Modes')], default='cash', max_length=20),
        ),
    ]
