# Generated by Django 5.2.8 on 2025-12-23 08:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenancy')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of times procedure is to be performed')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('bill_item_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the bill item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Procedure Order',
                'verbose_name_plural': 'Procedure Orders',
                'db_table': 'diag_procedure_orders',
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenancy')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the encounter record')),
                ('requisition_number', models.CharField(blank=True, help_text='Unique requisition identifier', max_length=50, unique=True)),
                ('requisition_type', models.CharField(choices=[('investigation', 'Investigation'), ('medicine', 'Medicine'), ('procedure', 'Procedure'), ('package', 'Package')], default='investigation', help_text='Type of requisition: investigation, medicine, procedure, or package', max_length=20)),
                ('requesting_doctor_id', models.UUIDField(db_index=True, help_text='SuperAdmin User ID of doctor who ordered the test')),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('sample_collected', 'Sample Collected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT (Immediate)')], default='routine', max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Requisition',
                'verbose_name_plural': 'Requisitions',
                'db_table': 'diag_requisitions',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenancy')),
                ('name', models.CharField(help_text="Test name (e.g., 'Complete Blood Count', 'Chest X-Ray')", max_length=200)),
                ('code', models.CharField(help_text="Unique test code (e.g., 'CBC', 'CXR')", max_length=50)),
                ('category', models.CharField(choices=[('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('pathology', 'Pathology'), ('cardiology', 'Cardiology'), ('ultrasound', 'Ultrasound'), ('ct_scan', 'CT Scan'), ('mri', 'MRI'), ('xray', 'X-Ray'), ('other', 'Other')], default='laboratory', max_length=50)),
                ('base_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base charge for this test', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Investigation',
                'verbose_name_plural': 'Investigations',
                'db_table': 'diag_investigations',
                'ordering': ['category', 'name'],
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DiagnosticOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenancy')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sample_collected', 'Sample Collected'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('sample_id', models.CharField(blank=True, help_text='Barcode or ID of the sample', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('bill_item_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the bill item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_item_content_type', models.ForeignKey(blank=True, help_text='Type of bill item (OPDBillItem or IPDBillItem)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='diagnostics.investigation')),
            ],
            options={
                'verbose_name': 'Diagnostic Order',
                'verbose_name_plural': 'Diagnostic Orders',
                'db_table': 'diag_orders',
            },
        ),
        migrations.CreateModel(
            name='InvestigationRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenancy')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], default='Any', max_length=20)),
                ('min_age', models.IntegerField(default=0, help_text='Minimum age in years')),
                ('max_age', models.IntegerField(default=120, help_text='Maximum age in years')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('text_reference', models.TextField(blank=True, help_text='Textual reference range if numerical is not applicable')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='diagnostics.investigation')),
            ],
            options={
                'verbose_name': 'Investigation Range',
                'verbose_name_plural': 'Investigation Ranges',
                'db_table': 'diag_investigation_ranges',
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenancy')),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Structured result data')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='diagnostics/reports/%Y/%m/')),
                ('technician_id', models.UUIDField(blank=True, help_text='User ID of the technician who entered results', null=True)),
                ('verified_by', models.UUIDField(blank=True, help_text='User ID of the doctor/pathologist who verified results', null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnostic_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='diagnostics.diagnosticorder')),
            ],
            options={
                'verbose_name': 'Lab Report',
                'verbose_name_plural': 'Lab Reports',
                'db_table': 'diag_lab_reports',
            },
        ),
        migrations.CreateModel(
            name='MedicineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenancy')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispensed', 'Dispensed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of medicine ordered')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('bill_item_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the bill item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_item_content_type', models.ForeignKey(blank=True, help_text='Type of bill item (OPDBillItem or IPDBillItem)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicine_orders', to='pharmacy.pharmacyproduct')),
            ],
            options={
                'verbose_name': 'Medicine Order',
                'verbose_name_plural': 'Medicine Orders',
                'db_table': 'diag_medicine_orders',
            },
        ),
        migrations.CreateModel(
            name='PackageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenancy')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of packages ordered')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('bill_item_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the bill item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_item_content_type', models.ForeignKey(blank=True, help_text='Type of bill item (OPDBillItem or IPDBillItem)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Package Order',
                'verbose_name_plural': 'Package Orders',
                'db_table': 'diag_package_orders',
            },
        ),
    ]
