# Generated by Django 5.2.9 on 2025-12-20 08:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('patients', '0003_alter_patientprofile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('name', models.CharField(help_text="Test name (e.g., 'Complete Blood Count', 'Chest X-Ray')", max_length=200)),
                ('code', models.CharField(help_text="Unique test code (e.g., 'CBC', 'CXR')", max_length=50)),
                ('category', models.CharField(choices=[('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('pathology', 'Pathology'), ('cardiology', 'Cardiology'), ('ultrasound', 'Ultrasound'), ('ct_scan', 'CT Scan'), ('mri', 'MRI'), ('xray', 'X-Ray'), ('ecg', 'ECG'), ('echo', 'Echocardiography'), ('endoscopy', 'Endoscopy'), ('biopsy', 'Biopsy'), ('other', 'Other')], default='laboratory', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the test')),
                ('sample_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('stool', 'Stool'), ('tissue', 'Tissue'), ('fluid', 'Body Fluid'), ('swab', 'Swab'), ('sputum', 'Sputum'), ('na', 'Not Applicable'), ('other', 'Other')], default='na', help_text='Type of sample required', max_length=50)),
                ('sample_quantity', models.CharField(blank=True, help_text="Sample quantity required (e.g., '5ml blood')", max_length=100)),
                ('preparation_instructions', models.TextField(blank=True, help_text="Patient preparation instructions (e.g., 'Fasting required')")),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Standard price for this test', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('turnaround_time_hours', models.IntegerField(default=24, help_text='Expected time to complete in hours', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this test is currently available')),
                ('requires_approval', models.BooleanField(default=False, help_text='Whether this test requires special approval')),
                ('reference_range', models.TextField(blank=True, help_text='Normal reference range for this test')),
                ('method', models.CharField(blank=True, help_text='Testing method/technique', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investigation',
                'verbose_name_plural': 'Investigations',
                'db_table': 'diagnostics_investigations',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['tenant_id'], name='diagnostics_tenant__46bdc7_idx'), models.Index(fields=['tenant_id', 'category'], name='diagnostics_tenant__2482e7_idx'), models.Index(fields=['tenant_id', 'is_active'], name='diagnostics_tenant__502054_idx'), models.Index(fields=['code'], name='investigation_code_idx'), models.Index(fields=['category'], name='investigation_category_idx')],
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenancy')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the encounter record')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requisition_number', models.CharField(help_text='Unique requisition identifier (e.g., REQ/20231223/001)', max_length=50, unique=True)),
                ('ordered_by_doctor_id', models.UUIDField(db_index=True, help_text='SuperAdmin User ID of doctor who ordered the test')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time test was ordered')),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT (Immediate)')], default='routine', max_length=20)),
                ('clinical_notes', models.TextField(blank=True, help_text='Clinical indication/notes for the test')),
                ('sample_collected_date', models.DateTimeField(blank=True, help_text='Date and time sample was collected', null=True)),
                ('collected_by_user_id', models.UUIDField(blank=True, db_index=True, help_text='User who collected the sample', null=True)),
                ('processing_started_date', models.DateTimeField(blank=True, help_text='Date and time processing started', null=True)),
                ('processed_by_user_id', models.UUIDField(blank=True, db_index=True, help_text='User who processed the test', null=True)),
                ('result_date', models.DateTimeField(blank=True, help_text='Date and time results were ready', null=True)),
                ('result_value', models.TextField(blank=True, help_text='Test result value')),
                ('result_unit', models.CharField(blank=True, help_text='Unit of measurement', max_length=50)),
                ('result_interpretation', models.TextField(blank=True, help_text='Interpretation of results (Normal/Abnormal/etc.)')),
                ('result_file', models.FileField(blank=True, help_text='Upload result report (PDF, image, etc.)', null=True, upload_to='diagnostics/results/%Y/%m/')),
                ('reported_by_user_id', models.UUIDField(blank=True, db_index=True, help_text='User who reported the results', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sample_collected', 'Sample Collected'), ('processing', 'Processing'), ('completed', 'Completed'), ('reported', 'Reported'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price charged for this test (copied from Investigation)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_billed', models.BooleanField(default=False, help_text='Whether this test has been added to billing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='Type of encounter (OPD Visit or IPD Admission)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='diagnostics.investigation')),
                ('patient', models.ForeignKey(help_text='Patient for whom test is ordered', on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='patients.patientprofile')),
            ],
            options={
                'verbose_name': 'Requisition',
                'verbose_name_plural': 'Requisitions',
                'db_table': 'diagnostics_requisitions',
                'ordering': ['-order_date'],
                'indexes': [models.Index(fields=['tenant_id'], name='diagnostics_tenant__4d59bd_idx'), models.Index(fields=['tenant_id', 'status'], name='diagnostics_tenant__5346b5_idx'), models.Index(fields=['tenant_id', 'order_date'], name='diagnostics_tenant__dc8b5d_idx'), models.Index(fields=['requisition_number'], name='requisition_number_idx'), models.Index(fields=['patient', 'order_date'], name='requisition_patient_date_idx'), models.Index(fields=['ordered_by_doctor_id'], name='requisition_doctor_idx'), models.Index(fields=['investigation'], name='requisition_investigation_idx'), models.Index(fields=['status'], name='requisition_status_idx'), models.Index(fields=['content_type', 'object_id'], name='requisition_encounter_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'investigation', 'order_date'), name='unique_requisition_per_encounter_investigation')],
            },
        ),
    ]
