# Generated by Django 5.2.8 on 2025-12-23 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('diagnostics', '0001_initial'),
        ('opd', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageorder',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_orders', to='opd.procedurepackage'),
        ),
        migrations.AddField(
            model_name='procedureorder',
            name='bill_item_content_type',
            field=models.ForeignKey(blank=True, help_text='Type of bill item (OPDBillItem or IPDBillItem)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='procedureorder',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedure_orders', to='opd.proceduremaster'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='content_type',
            field=models.ForeignKey(help_text='Type of encounter (OPD Visit or IPD Admission)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='procedureorder',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_orders', to='diagnostics.requisition'),
        ),
        migrations.AddField(
            model_name='packageorder',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_orders', to='diagnostics.requisition'),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_orders', to='diagnostics.requisition'),
        ),
        migrations.AddField(
            model_name='diagnosticorder',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='diagnostics.requisition'),
        ),
        migrations.AddIndex(
            model_name='procedureorder',
            index=models.Index(fields=['bill_item_content_type', 'bill_item_object_id'], name='diag_proced_bill_it_83e128_idx'),
        ),
        migrations.AddIndex(
            model_name='packageorder',
            index=models.Index(fields=['bill_item_content_type', 'bill_item_object_id'], name='diag_packag_bill_it_e8334a_idx'),
        ),
        migrations.AddIndex(
            model_name='medicineorder',
            index=models.Index(fields=['bill_item_content_type', 'bill_item_object_id'], name='diag_medici_bill_it_e841dd_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticorder',
            index=models.Index(fields=['bill_item_content_type', 'bill_item_object_id'], name='diag_orders_bill_it_8f9f56_idx'),
        ),
    ]
