# Generated by Django 5.2.9 on 2025-12-20 08:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
        ('patients', '0003_alter_patientprofile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenancy')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sample_collected', 'Sample Collected'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('sample_id', models.CharField(blank=True, help_text='Barcode or ID of the sample', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diagnostic Order',
                'verbose_name_plural': 'Diagnostic Orders',
                'db_table': 'diag_orders',
            },
        ),
        migrations.CreateModel(
            name='InvestigationRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenancy')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], default='Any', max_length=20)),
                ('min_age', models.IntegerField(default=0, help_text='Minimum age in years')),
                ('max_age', models.IntegerField(default=120, help_text='Maximum age in years')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('text_reference', models.TextField(blank=True, help_text='Textual reference range if numerical is not applicable')),
            ],
            options={
                'verbose_name': 'Investigation Range',
                'verbose_name_plural': 'Investigation Ranges',
                'db_table': 'diag_investigation_ranges',
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenancy')),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Structured result data')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='diagnostics/reports/%Y/%m/')),
                ('technician_id', models.UUIDField(blank=True, help_text='User ID of the technician who entered results', null=True)),
                ('verified_by', models.UUIDField(blank=True, help_text='User ID of the doctor/pathologist who verified results', null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lab Report',
                'verbose_name_plural': 'Lab Reports',
                'db_table': 'diag_lab_reports',
            },
        ),
        migrations.RemoveConstraint(
            model_name='requisition',
            name='unique_requisition_per_encounter_investigation',
        ),
        migrations.RemoveIndex(
            model_name='investigation',
            name='diagnostics_tenant__46bdc7_idx',
        ),
        migrations.RemoveIndex(
            model_name='investigation',
            name='diagnostics_tenant__2482e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='investigation',
            name='diagnostics_tenant__502054_idx',
        ),
        migrations.RemoveIndex(
            model_name='investigation',
            name='investigation_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='investigation',
            name='investigation_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='requisition',
            name='diagnostics_tenant__4d59bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='requisition',
            name='diagnostics_tenant__5346b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='requisition',
            name='diagnostics_tenant__dc8b5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='requisition',
            name='requisition_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='requisition',
            name='requisition_patient_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='requisition',
            name='requisition_doctor_idx',
        ),
        migrations.RemoveIndex(
            model_name='requisition',
            name='requisition_investigation_idx',
        ),
        migrations.RemoveIndex(
            model_name='requisition',
            name='requisition_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='requisition',
            name='requisition_encounter_idx',
        ),
        migrations.RenameField(
            model_name='requisition',
            old_name='ordered_by_doctor_id',
            new_name='requesting_doctor_id',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='method',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='preparation_instructions',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='reference_range',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='requires_approval',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='sample_quantity',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='sample_type',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='turnaround_time_hours',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='collected_by_user_id',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='investigation',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='is_billed',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='price',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='processed_by_user_id',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='processing_started_date',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='reported_by_user_id',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='result_date',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='result_file',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='result_interpretation',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='result_unit',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='result_value',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='sample_collected_date',
        ),
        migrations.AddField(
            model_name='investigation',
            name='base_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base charge for this test', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='category',
            field=models.CharField(choices=[('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('pathology', 'Pathology'), ('cardiology', 'Cardiology'), ('ultrasound', 'Ultrasound'), ('ct_scan', 'CT Scan'), ('mri', 'MRI'), ('xray', 'X-Ray'), ('other', 'Other')], default='laboratory', max_length=50),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='tenant_id',
            field=models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenancy'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='clinical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_number',
            field=models.CharField(blank=True, help_text='Unique requisition identifier', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('sample_collected', 'Sample Collected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=20),
        ),
        migrations.AlterModelTable(
            name='investigation',
            table='diag_investigations',
        ),
        migrations.AlterModelTable(
            name='requisition',
            table='diag_requisitions',
        ),
        migrations.AddField(
            model_name='diagnosticorder',
            name='investigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='diagnostics.investigation'),
        ),
        migrations.AddField(
            model_name='diagnosticorder',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='diagnostics.requisition'),
        ),
        migrations.AddField(
            model_name='investigationrange',
            name='investigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='diagnostics.investigation'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='diagnostic_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='diagnostics.diagnosticorder'),
        ),
    ]
