# Generated by Django 5.2.8 on 2025-12-21 16:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('diagnostics', '0002_diagnosticorder_investigationrange_labreport_and_more'),
        ('opd', '0005_finalize_encounter_migration'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenancy')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispensed', 'Dispensed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of medicine ordered')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the bill item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicine Order',
                'verbose_name_plural': 'Medicine Orders',
                'db_table': 'diag_medicine_orders',
            },
        ),
        migrations.CreateModel(
            name='PackageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenancy')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of packages ordered')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the bill item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Package Order',
                'verbose_name_plural': 'Package Orders',
                'db_table': 'diag_package_orders',
            },
        ),
        migrations.CreateModel(
            name='ProcedureOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenancy')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of times procedure is to be performed')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the bill item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Procedure Order',
                'verbose_name_plural': 'Procedure Orders',
                'db_table': 'diag_procedure_orders',
            },
        ),
        migrations.AddField(
            model_name='diagnosticorder',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Type of bill item (OPDBillItem or IPDBillItem)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='diagnosticorder',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the bill item', null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='requisition_type',
            field=models.CharField(choices=[('investigation', 'Investigation'), ('medicine', 'Medicine'), ('procedure', 'Procedure'), ('package', 'Package')], default='investigation', help_text='Type of requisition: investigation, medicine, procedure, or package', max_length=20),
        ),
        migrations.AddIndex(
            model_name='diagnosticorder',
            index=models.Index(fields=['content_type', 'object_id'], name='diag_orders_content_d861a5_idx'),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Type of bill item (OPDBillItem or IPDBillItem)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicine_orders', to='pharmacy.pharmacyproduct'),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_orders', to='diagnostics.requisition'),
        ),
        migrations.AddField(
            model_name='packageorder',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Type of bill item (OPDBillItem or IPDBillItem)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='packageorder',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_orders', to='opd.procedurepackage'),
        ),
        migrations.AddField(
            model_name='packageorder',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_orders', to='diagnostics.requisition'),
        ),
        migrations.AddField(
            model_name='procedureorder',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Type of bill item (OPDBillItem or IPDBillItem)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='procedureorder',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedure_orders', to='opd.proceduremaster'),
        ),
        migrations.AddField(
            model_name='procedureorder',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_orders', to='diagnostics.requisition'),
        ),
        migrations.AddIndex(
            model_name='medicineorder',
            index=models.Index(fields=['content_type', 'object_id'], name='diag_medici_content_45c02e_idx'),
        ),
        migrations.AddIndex(
            model_name='packageorder',
            index=models.Index(fields=['content_type', 'object_id'], name='diag_packag_content_868092_idx'),
        ),
        migrations.AddIndex(
            model_name='procedureorder',
            index=models.Index(fields=['content_type', 'object_id'], name='diag_proced_content_bdbf21_idx'),
        ),
    ]
