# Generated by Django 5.2.9 on 2026-03-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0003_investigation_import_export_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='code',
            field=models.CharField(blank=True, help_text="Unique test code (e.g., 'CBC', 'CXR'). Auto-generated if left blank.", max_length=50),
        ),
    ]
