# Generated by Django 5.2.8 on 2025-12-21 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('diagnostics', '0003_medicineorder_packageorder_procedureorder_and_more'),
        ('opd', '0005_finalize_encounter_migration'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='diagnosticorder',
            name='diag_orders_content_d861a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicineorder',
            name='diag_medici_content_45c02e_idx',
        ),
        migrations.RemoveIndex(
            model_name='packageorder',
            name='diag_packag_content_868092_idx',
        ),
        migrations.RemoveIndex(
            model_name='procedureorder',
            name='diag_proced_content_bdbf21_idx',
        ),
        migrations.RenameField(
            model_name='diagnosticorder',
            old_name='object_id',
            new_name='bill_item_object_id',
        ),
        migrations.RenameField(
            model_name='medicineorder',
            old_name='object_id',
            new_name='bill_item_object_id',
        ),
        migrations.RenameField(
            model_name='packageorder',
            old_name='object_id',
            new_name='bill_item_object_id',
        ),
        migrations.RenameField(
            model_name='procedureorder',
            old_name='object_id',
            new_name='bill_item_object_id',
        ),
        migrations.RemoveField(
            model_name='diagnosticorder',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='medicineorder',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='packageorder',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='procedureorder',
            name='content_type',
        ),
        migrations.AddField(
            model_name='diagnosticorder',
            name='bill_item_content_type',
            field=models.ForeignKey(blank=True, help_text='Type of bill item (OPDBillItem or IPDBillItem)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='bill_item_content_type',
            field=models.ForeignKey(blank=True, help_text='Type of bill item (OPDBillItem or IPDBillItem)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='packageorder',
            name='bill_item_content_type',
            field=models.ForeignKey(blank=True, help_text='Type of bill item (OPDBillItem or IPDBillItem)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='procedureorder',
            name='bill_item_content_type',
            field=models.ForeignKey(blank=True, help_text='Type of bill item (OPDBillItem or IPDBillItem)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='diagnosticorder',
            index=models.Index(fields=['bill_item_content_type', 'bill_item_object_id'], name='diag_orders_bill_it_8f9f56_idx'),
        ),
        migrations.AddIndex(
            model_name='medicineorder',
            index=models.Index(fields=['bill_item_content_type', 'bill_item_object_id'], name='diag_medici_bill_it_e841dd_idx'),
        ),
        migrations.AddIndex(
            model_name='packageorder',
            index=models.Index(fields=['bill_item_content_type', 'bill_item_object_id'], name='diag_packag_bill_it_e8334a_idx'),
        ),
        migrations.AddIndex(
            model_name='procedureorder',
            index=models.Index(fields=['bill_item_content_type', 'bill_item_object_id'], name='diag_proced_bill_it_83e128_idx'),
        ),
    ]
