# Generated by Django 5.2.9 on 2026-06-26 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalForm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(db_index=True, help_text='Stable machine identifier for MCP', max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_system', models.BooleanField(default=False, help_text='System forms are seeded and protected')),
                ('entity_type', models.CharField(choices=[('opd_visit', 'OPD Visit'), ('ipd_admission', 'IPD Admission'), ('generic', 'Generic')], default='generic', max_length=32)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Layout/display configuration')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'clinical_forms',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='clinical_fo_tenant__bca6e3_idx'), models.Index(fields=['tenant_id', 'entity_type'], name='clinical_fo_tenant__6a45f4_idx'), models.Index(fields=['tenant_id', 'is_system'], name='clinical_fo_tenant__b1e630_idx')],
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ClinicalFormSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_collapsed', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='clinical.clinicalform')),
            ],
            options={
                'db_table': 'clinical_form_sections',
                'ordering': ['form', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalPicklist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(db_index=True, help_text='Stable machine identifier', max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False, help_text='System picklists are seeded and protected')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'clinical_picklists',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'is_system'], name='clinical_pi_tenant__0084a5_idx')],
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ClinicalFormField',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('field_key', models.CharField(db_index=True, help_text='Stable identifier within the form', max_length=64)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Date Time'), ('picklist', 'Picklist'), ('multiselect', 'Multi-select'), ('file', 'File'), ('calculated', 'Calculated')], default='text', max_length=32)),
                ('label', models.CharField(max_length=255)),
                ('help_text', models.CharField(blank=True, default='', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('is_read_only', models.BooleanField(default=False)),
                ('default_value', models.JSONField(blank=True, default=None, null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Validation rules, display logic, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='clinical.clinicalformsection')),
                ('picklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_fields', to='clinical.clinicalpicklist')),
            ],
            options={
                'db_table': 'clinical_form_fields',
                'ordering': ['section', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalPicklistItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(db_index=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('picklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinical.clinicalpicklist')),
            ],
            options={
                'db_table': 'clinical_picklist_items',
                'ordering': ['picklist', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('encounter_type', models.CharField(db_index=True, help_text='e.g. opd_visit, ipd_admission', max_length=32)),
                ('encounter_id', models.PositiveIntegerField(db_index=True)),
                ('patient_user_id', models.UUIDField(blank=True, db_index=True, help_text='Optional denormalized patient UUID', null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('locked', 'Locked')], default='in_progress', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_by_user_id', models.UUIDField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='clinical.clinicalform')),
            ],
            options={
                'db_table': 'clinical_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalFieldValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_values', to='clinical.clinicalformfield')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='clinical.clinicalrecord')),
            ],
            options={
                'db_table': 'clinical_field_values',
                'ordering': ['record', 'field__display_order'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalRecordAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('locked', 'Locked'), ('unlocked', 'Unlocked'), ('snapshot_created', 'Snapshot Created'), ('field_values_upserted', 'Field Values Upserted')], max_length=32)),
                ('user_id', models.UUIDField(db_index=True, help_text='SuperAdmin User ID who performed the action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Ids and codes only; no field values')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='clinical.clinicalrecord')),
            ],
            options={
                'db_table': 'clinical_record_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedFormSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('snapshot_data', models.JSONField(default=dict, help_text='Serialized record + field values')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='clinical.clinicalrecord')),
            ],
            options={
                'db_table': 'clinical_saved_form_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFormPreference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True, help_text='SuperAdmin User ID')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Collapsed sections, default values, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='clinical.clinicalform')),
            ],
            options={
                'db_table': 'clinical_user_form_preferences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clinicalformsection',
            index=models.Index(fields=['tenant_id', 'form', 'display_order'], name='clinical_fo_tenant__937356_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicalformsection',
            unique_together={('tenant_id', 'form', 'code')},
        ),
        migrations.AddIndex(
            model_name='clinicalformfield',
            index=models.Index(fields=['tenant_id', 'section', 'display_order'], name='clinical_fo_tenant__793cee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicalformfield',
            unique_together={('tenant_id', 'section', 'field_key')},
        ),
        migrations.AddIndex(
            model_name='clinicalpicklistitem',
            index=models.Index(fields=['tenant_id', 'picklist', 'display_order'], name='clinical_pi_tenant__bec9f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicalpicklistitem',
            unique_together={('tenant_id', 'picklist', 'value')},
        ),
        migrations.AddIndex(
            model_name='clinicalrecord',
            index=models.Index(fields=['tenant_id', 'encounter_type', 'encounter_id'], name='clinical_re_tenant__a33b71_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalrecord',
            index=models.Index(fields=['tenant_id', 'status'], name='clinical_re_tenant__3f0a35_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalrecord',
            index=models.Index(fields=['tenant_id', 'patient_user_id'], name='clinical_re_tenant__d03e6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicalrecord',
            unique_together={('tenant_id', 'form', 'encounter_type', 'encounter_id')},
        ),
        migrations.AddIndex(
            model_name='clinicalfieldvalue',
            index=models.Index(fields=['tenant_id', 'record'], name='clinical_fi_tenant__af465e_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalfieldvalue',
            index=models.Index(fields=['tenant_id', 'field'], name='clinical_fi_tenant__c331fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicalfieldvalue',
            unique_together={('tenant_id', 'record', 'field')},
        ),
        migrations.AddIndex(
            model_name='clinicalrecordauditlog',
            index=models.Index(fields=['tenant_id', 'record', '-created_at'], name='clinical_re_tenant__8bc3df_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalrecordauditlog',
            index=models.Index(fields=['tenant_id', 'user_id'], name='clinical_re_tenant__2490d9_idx'),
        ),
        migrations.AddIndex(
            model_name='savedformsnapshot',
            index=models.Index(fields=['tenant_id', 'record'], name='clinical_sa_tenant__950783_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userformpreference',
            unique_together={('tenant_id', 'user_id', 'form')},
        ),
    ]
