# Generated by Django 5.2.9 on 2026-06-28 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_seed_hospital_system_forms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalFormGenerationRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('prompt', models.TextField(help_text='Natural-language description of the form to generate.')),
                ('extra_instructions', models.TextField(blank=True, default='', help_text='Additional constraints for the AI.')),
                ('entity_type', models.CharField(choices=[('opd_visit', 'OPD Visit'), ('ipd_admission', 'IPD Admission'), ('generic', 'Generic')], default='generic', help_text='The encounter type this form is meant for.', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('applied', 'Applied')], default='pending', max_length=20)),
                ('generated_draft', models.JSONField(blank=True, default=None, help_text='AI-generated form schema.', null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('applied_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generation_requests', to='clinical.clinicalform')),
            ],
            options={
                'db_table': 'clinical_form_generation_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='clinical_fo_tenant__8b1d7e_idx'), models.Index(fields=['tenant_id', 'applied_form'], name='clinical_fo_tenant__38941d_idx')],
            },
        ),
    ]
