# Generated by Django 5.2.9 on 2026-06-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_clinicalform_staging_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clinicalrecordauditlog',
            name='clinical_re_tenant__2490d9_idx',
        ),
        migrations.AddIndex(
            model_name='clinicalrecordauditlog',
            index=models.Index(fields=['tenant_id', '-created_at'], name='clinical_re_tenant__c87f2a_idx'),
        ),
    ]
