# Generated by Django 5.2.9 on 2026-06-30 19:24

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_sections_to_placements(apps, schema_editor):
    ClinicalFormSection = apps.get_model('clinical', 'ClinicalFormSection')
    FormSectionPlacement = apps.get_model('clinical', 'FormSectionPlacement')

    for section in ClinicalFormSection.objects.select_related('form').all():
        form = section.form
        if form is None:
            continue

        old_code = section.code
        prefixed_code = f"{form.code}_{old_code}"
        if len(prefixed_code) > 64:
            prefixed_code = f"{prefixed_code[:55]}_{section.id}"
        if section.code != prefixed_code:
            section.code = prefixed_code
            section.save(update_fields=['code'])

        FormSectionPlacement.objects.get_or_create(
            tenant_id=section.tenant_id,
            form_id=form.id,
            section_id=section.id,
            instance_key='',
            defaults={
                'display_order': getattr(section, 'display_order', 0),
                'is_collapsed': getattr(section, 'is_collapsed', False),
                'created_by_user_id': section.created_by_user_id,
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_remove_clinicalrecordauditlog_clinical_re_tenant__2490d9_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalDocumentInstance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('encounter_type', models.CharField(db_index=True, max_length=32)),
                ('encounter_id', models.PositiveIntegerField(db_index=True)),
                ('language', models.CharField(default='en', max_length=8)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('printed', 'Printed'), ('signed', 'Signed')], default='generated', max_length=20)),
                ('generated_pdf_url', models.URLField(blank=True, default='', max_length=1024)),
                ('printed_by_user_id', models.UUIDField(blank=True, null=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'clinical_document_instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('consent', 'Consent'), ('stationery', 'Stationery'), ('certificate', 'Certificate')], max_length=32)),
                ('bucket', models.CharField(default='none', max_length=32)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('requires_signature', models.BooleanField(default=False)),
                ('applicable_entity_types', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_system', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('body_ref', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'clinical_document_templates',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalFormGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('group_type', models.CharField(choices=[('drawer_section', 'Drawer Section'), ('tab_set', 'Tab Set'), ('workflow', 'Workflow'), ('left_rail', 'Left Rail')], default='drawer_section', max_length=32)),
                ('entity_type', models.CharField(choices=[('opd_visit', 'OPD Visit'), ('ipd_admission', 'IPD Admission'), ('generic', 'Generic')], default='generic', max_length=32)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_system', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'clinical_form_groups',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalFormGroupItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('badge_when_filled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'clinical_form_group_items',
                'ordering': ['group', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalPicklistGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'clinical_picklist_groups',
                'ordering': ['code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalPicklistGroupMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'clinical_picklist_group_memberships',
                'ordering': ['group', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalPrintTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('target_type', models.CharField(choices=[('form', 'Form'), ('document', 'Document')], max_length=32)),
                ('target_code', models.CharField(db_index=True, max_length=64)),
                ('layout', models.CharField(default='letterhead', max_length=32)),
                ('language', models.CharField(default='en', max_length=8)),
                ('html', models.TextField(blank=True, default='')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'clinical_print_templates',
                'ordering': ['target_type', 'target_code', 'language', 'layout'],
            },
        ),
        migrations.CreateModel(
            name='FormSectionPlacement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('instance_key', models.CharField(blank=True, default='', max_length=64)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('title_override', models.CharField(blank=True, default='', max_length=200)),
                ('is_collapsed', models.BooleanField(default=False)),
                ('visibility_rule', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'clinical_form_section_placements',
                'ordering': ['form', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MrdChecklistLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('bucket', models.CharField(default='gen', max_length=32)),
                ('source_type', models.CharField(choices=[('form', 'Form'), ('document', 'Document'), ('none', 'None')], default='none', max_length=32)),
                ('source_code', models.CharField(blank=True, default='', max_length=64)),
                ('applicable_entity_types', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'clinical_mrd_checklist_lines',
                'ordering': ['bucket', 'display_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='clinicalformsection',
            options={'ordering': ['code', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='clinicalformsection',
            name='clinical_fo_tenant__937356_idx',
        ),
        migrations.AddField(
            model_name='clinicalfieldvalue',
            name='picklist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_values', to='clinical.clinicalpicklistitem'),
        ),
        migrations.AddField(
            model_name='clinicalfieldvalue',
            name='value_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalfieldvalue',
            name='value_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalformfield',
            name='label_mr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clinicalformsection',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System sections are seeded and protected'),
        ),
        migrations.AddField(
            model_name='clinicalpicklistitem',
            name='label_hi',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clinicalpicklistitem',
            name='label_mr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='form_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='structure_snapshot',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalformfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Date Time'), ('picklist', 'Picklist'), ('multiselect', 'Multi-select'), ('file', 'File'), ('calculated', 'Calculated'), ('time', 'Time'), ('yes_no', 'Yes / No / NA'), ('grid', 'Grid'), ('signature', 'Signature'), ('heading', 'Heading'), ('data_ref', 'Data Reference'), ('rich_text', 'Rich Text')], default='text', max_length=32),
        ),
        migrations.AddIndex(
            model_name='clinicalfieldvalue',
            index=models.Index(fields=['tenant_id', 'picklist_item'], name='clinical_fi_tenant__9f5640_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalformsection',
            index=models.Index(fields=['tenant_id', 'code'], name='clinical_fo_tenant__f93eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalformsection',
            index=models.Index(fields=['tenant_id', 'is_system'], name='clinical_fo_tenant__4d713e_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaldocumenttemplate',
            index=models.Index(fields=['tenant_id', 'doc_type', 'bucket'], name='clinical_do_tenant__130c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaldocumenttemplate',
            index=models.Index(fields=['tenant_id', 'is_system'], name='clinical_do_tenant__508b6d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicaldocumenttemplate',
            unique_together={('tenant_id', 'code')},
        ),
        migrations.AddField(
            model_name='clinicaldocumentinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='clinical.clinicaldocumenttemplate'),
        ),
        migrations.AddField(
            model_name='clinicalformgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='clinical.clinicalformgroup'),
        ),
        migrations.AddField(
            model_name='clinicalformgroupitem',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='clinical.clinicalform'),
        ),
        migrations.AddField(
            model_name='clinicalformgroupitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinical.clinicalformgroup'),
        ),
        migrations.AddIndex(
            model_name='clinicalpicklistgroup',
            index=models.Index(fields=['tenant_id', 'is_system'], name='clinical_pi_tenant__b87527_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicalpicklistgroup',
            unique_together={('tenant_id', 'code')},
        ),
        migrations.AddField(
            model_name='clinicalpicklistgroupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clinical.clinicalpicklistgroup'),
        ),
        migrations.AddField(
            model_name='clinicalpicklistgroupmembership',
            name='picklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='clinical.clinicalpicklist'),
        ),
        migrations.AddIndex(
            model_name='clinicalprinttemplate',
            index=models.Index(fields=['tenant_id', 'target_type', 'target_code'], name='clinical_pr_tenant__96b3b7_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalprinttemplate',
            index=models.Index(fields=['tenant_id', 'language', 'layout'], name='clinical_pr_tenant__3676a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicalprinttemplate',
            unique_together={('tenant_id', 'code')},
        ),
        migrations.AddField(
            model_name='formsectionplacement',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_placements', to='clinical.clinicalform'),
        ),
        migrations.AddField(
            model_name='formsectionplacement',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='form_placements', to='clinical.clinicalformsection'),
        ),
        migrations.RunPython(migrate_existing_sections_to_placements, noop_reverse),
        migrations.AlterUniqueTogether(
            name='clinicalformsection',
            unique_together={('tenant_id', 'code')},
        ),
        migrations.AddIndex(
            model_name='mrdchecklistline',
            index=models.Index(fields=['tenant_id', 'bucket', 'display_order'], name='clinical_mr_tenant__ec6897_idx'),
        ),
        migrations.AddIndex(
            model_name='mrdchecklistline',
            index=models.Index(fields=['tenant_id', 'source_type', 'source_code'], name='clinical_mr_tenant__71d18a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mrdchecklistline',
            unique_together={('tenant_id', 'code')},
        ),
        migrations.RemoveField(
            model_name='clinicalformsection',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='clinicalformsection',
            name='form',
        ),
        migrations.RemoveField(
            model_name='clinicalformsection',
            name='is_collapsed',
        ),
        migrations.AddIndex(
            model_name='clinicaldocumentinstance',
            index=models.Index(fields=['tenant_id', 'encounter_type', 'encounter_id'], name='clinical_do_tenant__7a9a97_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaldocumentinstance',
            index=models.Index(fields=['tenant_id', 'template', 'status'], name='clinical_do_tenant__b6a74f_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalformgroup',
            index=models.Index(fields=['tenant_id', 'entity_type', 'display_order'], name='clinical_fo_tenant__59da0a_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalformgroup',
            index=models.Index(fields=['tenant_id', 'parent', 'display_order'], name='clinical_fo_tenant__04d1de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicalformgroup',
            unique_together={('tenant_id', 'code')},
        ),
        migrations.AddIndex(
            model_name='clinicalformgroupitem',
            index=models.Index(fields=['tenant_id', 'group', 'display_order'], name='clinical_fo_tenant__a8ba7b_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalformgroupitem',
            index=models.Index(fields=['tenant_id', 'form'], name='clinical_fo_tenant__38b618_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicalformgroupitem',
            unique_together={('tenant_id', 'group', 'form')},
        ),
        migrations.AddIndex(
            model_name='clinicalpicklistgroupmembership',
            index=models.Index(fields=['tenant_id', 'group', 'display_order'], name='clinical_pi_tenant__718cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalpicklistgroupmembership',
            index=models.Index(fields=['tenant_id', 'picklist'], name='clinical_pi_tenant__cb608d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicalpicklistgroupmembership',
            unique_together={('tenant_id', 'group', 'picklist')},
        ),
        migrations.AddIndex(
            model_name='formsectionplacement',
            index=models.Index(fields=['tenant_id', 'form', 'display_order'], name='clinical_fo_tenant__1944ad_idx'),
        ),
        migrations.AddIndex(
            model_name='formsectionplacement',
            index=models.Index(fields=['tenant_id', 'section'], name='clinical_fo_tenant__560a69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formsectionplacement',
            unique_together={('tenant_id', 'form', 'section', 'instance_key')},
        ),
    ]
