# Generated by Django 5.2.9 on 2026-07-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0010_clinicalformtemplate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clinicalformtemplate',
            new_name='clinical_fo_tenant__29b22e_idx',
            old_name='clinical_fo_tenant__tmpl_idx',
        ),
        migrations.AlterField(
            model_name='clinicalformtemplate',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
