# Generated by Django 5.2.9 on 2026-07-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0011_rename_clinical_fo_tenant__tmpl_idx_clinical_fo_tenant__29b22e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalformfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Date Time'), ('picklist', 'Picklist'), ('multiselect', 'Multi-select'), ('file', 'File'), ('calculated', 'Calculated'), ('time', 'Time'), ('yes_no', 'Yes / No / NA'), ('grid', 'Grid'), ('signature', 'Signature'), ('heading', 'Heading'), ('data_ref', 'Data Reference'), ('rich_text', 'Rich Text'), ('api_select', 'API Select'), ('pain_faces', 'Pain Faces Scale'), ('body_diagram', 'Body Diagram')], default='text', max_length=32),
        ),
    ]
