"""System picklists + picklist groups (foundation).

Confirmed items where the source papers are explicit; a few placeholders
(diagnosis, medicine) to light up the UI — corrected from the live recording later.
Marathi (label_mr) filled where confidently known.
"""

PICKLISTS = [
    # ---- core toggles ---------------------------------------------------
    {
        "code": "yes_no",
        "name": "Yes / No",
        "description": "Binary yes/no choice.",
        "is_system": True,
        "items": [
            {"label": "Yes", "value": "yes", "label_mr": "होय"},
            {"label": "No", "value": "no", "label_mr": "नाही"},
        ],
    },
    {
        "code": "yes_no_na",
        "name": "Yes / No / NA",
        "description": "Three-state choice for checklists.",
        "is_system": True,
        "items": [
            {"label": "Yes", "value": "yes", "label_mr": "होय"},
            {"label": "No", "value": "no", "label_mr": "नाही"},
            {"label": "Not Applicable", "value": "na", "label_mr": "लागू नाही"},
        ],
    },
    {
        "code": "pain_scale",
        "name": "Pain Scale (0-10)",
        "description": "Numeric pain scale from 0 to 10.",
        "is_system": True,
        "items": [
            {"label": "0 - No pain", "value": "0"},
            {"label": "1", "value": "1"}, {"label": "2", "value": "2"},
            {"label": "3", "value": "3"}, {"label": "4", "value": "4"},
            {"label": "5", "value": "5"}, {"label": "6", "value": "6"},
            {"label": "7", "value": "7"}, {"label": "8", "value": "8"},
            {"label": "9", "value": "9"}, {"label": "10 - Worst pain", "value": "10"},
        ],
    },
    # ---- discharge ------------------------------------------------------
    {
        "code": "discharge_type",
        "name": "Discharge Type",
        "description": "Type of discharge (Regular / Transfer / DAMA / Death / On Request / Absconded).",
        "is_system": True,
        "items": [
            {"label": "Regular", "value": "regular"},
            {"label": "Transfer", "value": "transfer"},
            {"label": "DAMA (Against Medical Advice)", "value": "dama"},
            {"label": "Death", "value": "death"},
            {"label": "On Request", "value": "on_request"},
            {"label": "Absconded", "value": "absconded"},
        ],
    },
    {
        "code": "discharge_status",
        "name": "Discharge Status (MRD)",
        "description": "MRD checklist discharge status.",
        "is_system": True,
        "items": [
            {"label": "Discharge to Home", "value": "discharge_home"},
            {"label": "Transfer to Another Facility", "value": "transfer"},
            {"label": "DAMA", "value": "dama"},
            {"label": "LAMA", "value": "lama"},
            {"label": "Death", "value": "death"},
            {"label": "Absconded", "value": "absconded"},
        ],
    },
    {
        "code": "condition_at_discharge",
        "name": "Condition at Discharge",
        "description": "Patient condition at the time of discharge.",
        "is_system": True,
        "items": [
            {"label": "Cured", "value": "cured"},
            {"label": "Improved", "value": "improved"},
            {"label": "Not Improved", "value": "not_improved"},
            {"label": "Stable", "value": "stable"},
        ],
    },
    # ---- complaints / history ------------------------------------------
    {
        "code": "chief_complaints",
        "name": "Chief Complaints",
        "description": "Common presenting complaints. Tenants can add more.",
        "is_system": True,
        "items": [
            {"label": "Fever", "value": "fever", "label_mr": "ताप"},
            {"label": "Cold", "value": "cold", "label_mr": "सर्दी"},
            {"label": "Cough", "value": "cough", "label_mr": "खोकला"},
            {"label": "Sore Throat", "value": "sore_throat"},
            {"label": "Abdomen Pain", "value": "abdomen_pain", "label_mr": "पोटदुखी"},
            {"label": "Epigastric Pain", "value": "epigastric_pain"},
            {"label": "Chest Pain", "value": "chest_pain", "label_mr": "छातीत दुखणे"},
            {"label": "Breathlessness", "value": "breathlessness", "label_mr": "श्वास घेण्यास त्रास"},
            {"label": "Headache", "value": "headache", "label_mr": "डोकेदुखी"},
            {"label": "Vomiting", "value": "vomiting", "label_mr": "उलटी"},
            {"label": "Nausea", "value": "nausea"},
            {"label": "Diarrhoea", "value": "diarrhoea", "label_mr": "जुलाब"},
            {"label": "Constipation", "value": "constipation"},
            {"label": "Weakness", "value": "weakness", "label_mr": "अशक्तपणा"},
            {"label": "Giddiness / Dizziness", "value": "giddiness", "label_mr": "चक्कर"},
            {"label": "Body Ache", "value": "body_ache", "label_mr": "अंगदुखी"},
            {"label": "Burning Micturition", "value": "burning_micturition"},
            {"label": "Swelling", "value": "swelling", "label_mr": "सूज"},
            {"label": "Rash / Skin Eruptions", "value": "rash"},
            {"label": "Joint Pain", "value": "joint_pain", "label_mr": "सांधेदुखी"},
            {"label": "Back Pain", "value": "back_pain", "label_mr": "पाठदुखी"},
            {"label": "Palpitations", "value": "palpitations"},
            {"label": "Loss of Appetite", "value": "loss_of_appetite"},
            {"label": "Weight Loss", "value": "weight_loss"},
        ],
    },
    {
        "code": "past_history",
        "name": "Past History",
        "description": "Known comorbidities / past history snippets.",
        "is_system": True,
        "items": [
            {"label": "No known comorbidities", "value": "none_known"},
            {"label": "Diabetes Mellitus (DM)", "value": "dm"},
            {"label": "Hypertension (HTN)", "value": "htn"},
            {"label": "Ischemic Heart Disease (IHD)", "value": "ihd"},
            {"label": "Asthma / COPD", "value": "asthma_copd"},
            {"label": "Thyroid Disorder", "value": "thyroid"},
            {"label": "Tuberculosis (TB)", "value": "tb"},
            {"label": "Epilepsy / Seizure", "value": "epilepsy"},
            {"label": "CKD / Renal Disease", "value": "ckd"},
            {"label": "Hypothyroidism", "value": "hypothyroid"},
            {"label": "Previous Surgery", "value": "prev_surgery"},
            {"label": "Drug Allergy", "value": "drug_allergy"},
        ],
    },
    {
        "code": "admission_history",
        "name": "Admission History",
        "description": "Common admission-history snippets for discharge summary.",
        "is_system": True,
        "items": [
            {"label": "Patient admitted with above complaints", "value": "admitted_with_complaints"},
            {"label": "Patient was conscious and oriented", "value": "conscious_oriented"},
            {"label": "Vitals stable at admission", "value": "vitals_stable"},
            {"label": "Patient admitted in emergency", "value": "emergency_admission"},
            {"label": "Referred from outside hospital", "value": "referred_outside"},
        ],
    },
    {
        "code": "course_in_hospital",
        "name": "Course in Hospital",
        "description": "Common course-in-hospital snippets.",
        "is_system": True,
        "items": [
            {"label": "Patient was treated conservatively", "value": "conservative"},
            {"label": "Patient responded well to treatment", "value": "responded_well"},
            {"label": "Underwent surgery as planned", "value": "underwent_surgery"},
            {"label": "Monitored in ICU", "value": "icu_monitored"},
            {"label": "Stable throughout the stay", "value": "stable_stay"},
        ],
    },
    {
        "code": "treatment_given",
        "name": "Treatment Given",
        "description": "Common treatment-given snippets.",
        "is_system": True,
        "items": [
            {"label": "IV Fluids", "value": "iv_fluids"},
            {"label": "IV Antibiotics", "value": "iv_antibiotics"},
            {"label": "Analgesics", "value": "analgesics"},
            {"label": "Antipyretics", "value": "antipyretics"},
            {"label": "Antiemetics", "value": "antiemetics"},
            {"label": "PPI / Antacids", "value": "ppi"},
            {"label": "Supportive care", "value": "supportive"},
            {"label": "Oxygen support", "value": "oxygen"},
            {"label": "Nebulization", "value": "nebulization"},
        ],
    },
    {
        "code": "special_instructions",
        "name": "Special Instructions",
        "description": "Common special instructions at discharge.",
        "is_system": True,
        "items": [
            {"label": "Continue medicines as advised", "value": "continue_meds"},
            {"label": "Review with reports", "value": "review_with_reports"},
            {"label": "Suture removal after 7 days", "value": "suture_removal_7"},
            {"label": "Dressing on alternate days", "value": "dressing_alternate"},
            {"label": "Strict bed rest", "value": "strict_bed_rest"},
            {"label": "Report immediately if fever/pain increases", "value": "report_worsening"},
        ],
    },
    {
        "code": "discharge_advice",
        "name": "Discharge / Consultation Advice",
        "description": "Common advice at consultation or discharge.",
        "is_system": True,
        "items": [
            {"label": "Soft Diet", "value": "soft_diet"},
            {"label": "Normal Diet", "value": "normal_diet"},
            {"label": "Liquid Diet", "value": "liquid_diet"},
            {"label": "Low Salt Diet", "value": "low_salt_diet"},
            {"label": "Diabetic Diet", "value": "diabetic_diet"},
            {"label": "High Protein Diet", "value": "high_protein_diet"},
            {"label": "Drink Plenty of Water", "value": "plenty_water"},
            {"label": "Complete Bed Rest", "value": "bed_rest"},
            {"label": "Avoid Exertion / Heavy Work", "value": "avoid_exertion"},
            {"label": "Wound Care at Home", "value": "wound_care"},
            {"label": "Keep Wound Dry", "value": "keep_wound_dry"},
            {"label": "Follow Up as Advised", "value": "follow_up"},
            {"label": "Report if Symptoms Worsen", "value": "report_worsening"},
            {"label": "Avoid Spicy / Oily Food", "value": "avoid_spicy"},
            {"label": "No Alcohol / Smoking", "value": "no_alcohol_smoking"},
        ],
    },
    # ---- medication -----------------------------------------------------
    {
        "code": "medication_type",
        "name": "Medication Type",
        "description": "Dosage form / type for prescription grid.",
        "is_system": True,
        "items": [
            {"label": "Tablet", "value": "tablet"},
            {"label": "Capsule", "value": "capsule"},
            {"label": "Syrup", "value": "syrup"},
            {"label": "Injection", "value": "injection"},
            {"label": "Ointment / Cream", "value": "ointment"},
            {"label": "Drops", "value": "drops"},
            {"label": "Inhaler", "value": "inhaler"},
            {"label": "Sachet", "value": "sachet"},
        ],
    },
    {
        "code": "medicine",
        "name": "Medicine",
        "description": "Placeholder medicine list — replace from live data.",
        "is_system": True,
        "items": [
            {"label": "Paracetamol 500mg", "value": "paracetamol_500"},
            {"label": "Pantoprazole 40mg", "value": "pantoprazole_40"},
            {"label": "Ondansetron 4mg", "value": "ondansetron_4"},
            {"label": "Amoxicillin-Clavulanate 625mg", "value": "amox_clav_625"},
            {"label": "Azithromycin 500mg", "value": "azithromycin_500"},
            {"label": "Diclofenac 50mg", "value": "diclofenac_50"},
            {"label": "Cefixime 200mg", "value": "cefixime_200"},
            {"label": "Metronidazole 400mg", "value": "metronidazole_400"},
            {"label": "Ranitidine 150mg", "value": "ranitidine_150"},
            {"label": "Multivitamin", "value": "multivitamin"},
        ],
    },
    {
        "code": "dose_qty",
        "name": "Dose / Quantity",
        "description": "Dose quantity options.",
        "is_system": True,
        "items": [
            {"label": "1/2", "value": "0.5"},
            {"label": "1", "value": "1"},
            {"label": "2", "value": "2"},
            {"label": "5 ml", "value": "5ml"},
            {"label": "10 ml", "value": "10ml"},
            {"label": "15 ml", "value": "15ml"},
            {"label": "1 Sachet", "value": "1_sachet"},
        ],
    },
    {
        "code": "frequency",
        "name": "Frequency",
        "description": "Dosing frequency.",
        "is_system": True,
        "items": [
            {"label": "OD (Once a day)", "value": "od"},
            {"label": "BD (Twice a day)", "value": "bd"},
            {"label": "TDS (Thrice a day)", "value": "tds"},
            {"label": "QID (Four times a day)", "value": "qid"},
            {"label": "HS (At bedtime)", "value": "hs"},
            {"label": "SOS (When required)", "value": "sos"},
            {"label": "STAT (Immediately)", "value": "stat"},
            {"label": "Q6H", "value": "q6h"},
            {"label": "Q8H", "value": "q8h"},
            {"label": "Weekly", "value": "weekly"},
        ],
    },
    {
        "code": "medicine_instruction",
        "name": "Medicine Instruction",
        "description": "Intake instruction.",
        "is_system": True,
        "items": [
            {"label": "After Food", "value": "after_food", "label_mr": "जेवणानंतर"},
            {"label": "Before Food", "value": "before_food", "label_mr": "जेवणापूर्वी"},
            {"label": "With Food", "value": "with_food"},
            {"label": "Empty Stomach", "value": "empty_stomach", "label_mr": "उपाशीपोटी"},
            {"label": "With Milk", "value": "with_milk"},
            {"label": "With Warm Water", "value": "with_warm_water"},
        ],
    },
    {
        "code": "route_of_administration",
        "name": "Route of Administration",
        "description": "Drug administration routes.",
        "is_system": True,
        "items": [
            {"label": "Oral (PO)", "value": "oral"},
            {"label": "Intravenous (IV)", "value": "iv"},
            {"label": "Intramuscular (IM)", "value": "im"},
            {"label": "Subcutaneous (SC)", "value": "sc"},
            {"label": "Topical", "value": "topical"},
            {"label": "Inhalation", "value": "inhalation"},
            {"label": "Sublingual (SL)", "value": "sublingual"},
        ],
    },
    # ---- diagnosis / investigations ------------------------------------
    {
        "code": "diagnosis",
        "name": "Diagnosis",
        "description": "Placeholder diagnosis list — replace from live data.",
        "is_system": True,
        "items": [
            {"label": "Acute Gastroenteritis", "value": "age"},
            {"label": "Acute Febrile Illness", "value": "afi"},
            {"label": "Dengue Fever", "value": "dengue"},
            {"label": "Enteric Fever", "value": "enteric_fever"},
            {"label": "Lower Respiratory Tract Infection", "value": "lrti"},
            {"label": "Urinary Tract Infection", "value": "uti"},
            {"label": "Acute Appendicitis", "value": "appendicitis"},
            {"label": "Cholelithiasis", "value": "cholelithiasis"},
            {"label": "Type 2 Diabetes Mellitus", "value": "t2dm"},
            {"label": "Hypertension", "value": "htn"},
            {"label": "Anaemia", "value": "anaemia"},
            {"label": "Acute Pancreatitis", "value": "pancreatitis"},
        ],
    },
    {
        "code": "investigations",
        "name": "Investigations",
        "description": "Common laboratory investigations.",
        "is_system": True,
        "items": [
            {"label": "CBC", "value": "cbc"},
            {"label": "Dengue NS1 / IgM IgG", "value": "dengue"},
            {"label": "Malaria Antigen / Smear", "value": "malaria"},
            {"label": "COVID-19 RTPCR", "value": "covid_rtpcr"},
            {"label": "Prothrombin Time (PT / INR)", "value": "pt_inr"},
            {"label": "Coagulation Profile (APTT)", "value": "aptt"},
            {"label": "LFT", "value": "lft"},
            {"label": "RFT / KFT", "value": "rft"},
            {"label": "Serum Electrolytes", "value": "electrolytes"},
            {"label": "Serum Uric Acid", "value": "uric_acid"},
            {"label": "Serum Calcium", "value": "calcium"},
            {"label": "Vitamin D3", "value": "vit_d3"},
            {"label": "USG Abdomen", "value": "usg_abdomen"},
            {"label": "X-Ray Chest", "value": "xray_chest"},
            {"label": "ECG", "value": "ecg"},
            {"label": "2D Echo", "value": "echo"},
        ],
    },
    {
        "code": "lab_tests",
        "name": "Lab Tests (Initial Assessment grid)",
        "description": "Lab parameters used in initial-assessment lab grid.",
        "is_system": True,
        "items": [
            {"label": "HB", "value": "hb"}, {"label": "BT", "value": "bt"},
            {"label": "CT", "value": "ct"}, {"label": "PCV", "value": "pcv"},
            {"label": "PTT", "value": "ptt"}, {"label": "Platelets", "value": "platelets"},
            {"label": "ESR", "value": "esr"}, {"label": "INR", "value": "inr"},
            {"label": "TLC", "value": "tlc"}, {"label": "PT", "value": "pt"},
            {"label": "SGOT", "value": "sgot"}, {"label": "SGPT", "value": "sgpt"},
            {"label": "HIV", "value": "hiv"}, {"label": "TSH", "value": "tsh"},
            {"label": "BSL-F", "value": "bsl_f"}, {"label": "BSL-PP", "value": "bsl_pp"},
        ],
    },
    # ---- anaesthesia / surgery -----------------------------------------
    {
        "code": "anesthesia_type",
        "name": "Anaesthesia Type",
        "description": "Type of anaesthesia.",
        "is_system": True,
        "items": [
            {"label": "General Anaesthesia (GA)", "value": "ga"},
            {"label": "Spinal Anaesthesia (SA)", "value": "sa"},
            {"label": "Local Anaesthesia (LA)", "value": "la"},
            {"label": "Regional", "value": "regional"},
            {"label": "Short GA", "value": "short_ga"},
            {"label": "Epidural", "value": "epidural"},
            {"label": "MAC (Monitored Anaesthesia Care)", "value": "mac"},
        ],
    },
    {
        "code": "asa_grade",
        "name": "ASA Grade",
        "description": "ASA physical status classification.",
        "is_system": True,
        "items": [
            {"label": "ASA I", "value": "1"}, {"label": "ASA II", "value": "2"},
            {"label": "ASA III", "value": "3"}, {"label": "ASA IV", "value": "4"},
            {"label": "ASA V", "value": "5"}, {"label": "ASA VI", "value": "6"},
            {"label": "ASA I E (Emergency)", "value": "1e"},
            {"label": "ASA II E (Emergency)", "value": "2e"},
        ],
    },
    {
        "code": "surgical_position",
        "name": "Surgical Position",
        "description": "Patient position on table.",
        "is_system": True,
        "items": [
            {"label": "Supine", "value": "supine"},
            {"label": "Supine Beach Chair", "value": "beach_chair"},
            {"label": "Prone", "value": "prone"},
            {"label": "Lateral", "value": "lateral"},
            {"label": "Lithotomy", "value": "lithotomy"},
            {"label": "Trendelenburg", "value": "trendelenburg"},
        ],
    },
    {
        "code": "incision_type",
        "name": "Incision / Closure Type",
        "description": "Incision and skin-closure types.",
        "is_system": True,
        "items": [
            {"label": "Midline", "value": "midline"},
            {"label": "Pfannenstiel", "value": "pfannenstiel"},
            {"label": "Transverse", "value": "transverse"},
            {"label": "Paramedian", "value": "paramedian"},
            {"label": "Laparoscopic Ports", "value": "laparoscopic"},
            {"label": "Interrupted Simple", "value": "interrupted_simple"},
            {"label": "Mattress", "value": "mattress"},
            {"label": "Continuous", "value": "continuous"},
        ],
    },
    # ---- admin / demographics ------------------------------------------
    {
        "code": "relation",
        "name": "Relation",
        "description": "Guardian / relative relation.",
        "is_system": True,
        "items": [
            {"label": "Father", "value": "father", "label_mr": "वडील"},
            {"label": "Mother", "value": "mother", "label_mr": "आई"},
            {"label": "Spouse", "value": "spouse", "label_mr": "जोडीदार"},
            {"label": "Husband", "value": "husband", "label_mr": "पती"},
            {"label": "Wife", "value": "wife", "label_mr": "पत्नी"},
            {"label": "Son", "value": "son", "label_mr": "मुलगा"},
            {"label": "Daughter", "value": "daughter", "label_mr": "मुलगी"},
            {"label": "Brother", "value": "brother", "label_mr": "भाऊ"},
            {"label": "Sister", "value": "sister", "label_mr": "बहीण"},
            {"label": "Friend", "value": "friend"},
            {"label": "Guardian", "value": "guardian"},
            {"label": "Other", "value": "other", "label_mr": "इतर"},
        ],
    },
    {
        "code": "patient_category",
        "name": "Patient Category",
        "description": "Payment / scheme category.",
        "is_system": True,
        "items": [
            {"label": "Patient Paying", "value": "paying"},
            {"label": "Mediclaim / Insurance", "value": "mediclaim"},
            {"label": "MJPJAY", "value": "mjpjay"},
            {"label": "PMJAY (Ayushman)", "value": "pmjay"},
            {"label": "Corporate / TPA", "value": "corporate"},
            {"label": "Camp", "value": "camp"},
            {"label": "Staff", "value": "staff"},
        ],
    },
    {
        "code": "referral_source",
        "name": "Referred By",
        "description": "Source of referral.",
        "is_system": True,
        "items": [
            {"label": "Self", "value": "self"},
            {"label": "OPD", "value": "opd"},
            {"label": "Casualty / Emergency", "value": "casualty"},
            {"label": "Referred by Doctor", "value": "doctor_referral"},
            {"label": "Another Hospital", "value": "another_hospital"},
            {"label": "Health Camp", "value": "camp"},
        ],
    },
]


PICKLIST_GROUPS = [
    {
        "code": "discharge_lists",
        "name": "Discharge Card Lists",
        "description": "Picklists used across the discharge card.",
        "is_system": True,
        "picklists": [
            "diagnosis", "admission_history", "past_history", "course_in_hospital",
            "treatment_given", "condition_at_discharge", "special_instructions",
            "discharge_advice", "discharge_type",
        ],
    },
    {
        "code": "prescription_lists",
        "name": "Prescription Lists",
        "description": "Picklists used in the medicine/prescription grid.",
        "is_system": True,
        "picklists": [
            "medication_type", "medicine", "dose_qty", "frequency",
            "medicine_instruction", "route_of_administration",
        ],
    },
    {
        "code": "operative_lists",
        "name": "Operative / Anaesthesia Lists",
        "description": "Picklists used in operative and anaesthesia forms.",
        "is_system": True,
        "picklists": ["anesthesia_type", "asa_grade", "surgical_position", "incision_type"],
    },
    {
        "code": "assessment_lists",
        "name": "Assessment Lists",
        "description": "Picklists used in initial assessment.",
        "is_system": True,
        "picklists": ["chief_complaints", "past_history", "investigations", "lab_tests", "pain_scale"],
    },
    {
        "code": "admin_lists",
        "name": "Admission / Admin Lists",
        "description": "Demographic and admin picklists.",
        "is_system": True,
        "picklists": ["relation", "patient_category", "referral_source"],
    },
]
