# Generated by Django 5.2.8 on 2025-12-23 08:25

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20)),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by_id', models.UUIDField(blank=True, help_text='User who closed this period', null=True)),
            ],
            options={
                'verbose_name': 'Accounting Period',
                'verbose_name_plural': 'Accounting Periods',
                'db_table': 'accounting_periods',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['tenant_id'], name='accounting__tenant__30c2e2_idx'), models.Index(fields=['tenant_id', 'start_date', 'end_date'], name='accounting__tenant__4c15f9_idx'), models.Index(fields=['tenant_id', 'is_closed'], name='accounting__tenant__33eb63_idx')],
                'unique_together': {('name', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('refund', 'Refund'), ('adjustment', 'Accounting Adjustment')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment Category',
                'verbose_name_plural': 'Payment Categories',
                'db_table': 'payment_categories',
                'indexes': [models.Index(fields=['tenant_id'], name='payment_cat_tenant__cbdea9_idx'), models.Index(fields=['tenant_id', 'category_type'], name='payment_cat_tenant__1bd9e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('transaction_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment Received'), ('refund', 'Refund Issued'), ('expense', 'Expense'), ('adjustment', 'Accounting Adjustment')], max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('net_banking', 'Net Banking'), ('online', 'Online Payment'), ('cheque', 'Cheque'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=20, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('user_id', models.UUIDField(blank=True, help_text='User associated with this transaction', null=True)),
                ('description', models.TextField(blank=True, help_text='Transaction description or notes', null=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_by_id', models.UUIDField(blank=True, help_text='User who reconciled this transaction', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.paymentcategory')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id'], name='transaction_tenant__133f32_idx'), models.Index(fields=['tenant_id', 'transaction_type'], name='transaction_tenant__d71d6f_idx'), models.Index(fields=['tenant_id', 'created_at'], name='transaction_tenant__fb4178_idx'), models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx'), models.Index(fields=['category'], name='transaction_categor_bf503b_idx')],
            },
        ),
    ]
