# Generated by Django 5.2.9 on 2025-12-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('net_banking', 'Net Banking'), ('online', 'Online Payment'), ('razorpay', 'Razorpay'), ('cheque', 'Cheque'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
