# Generated by Django 5.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_transaction_payment_method'),
    ]

    operations = [
        # Remove the global unique constraint on name
        migrations.AlterField(
            model_name='paymentcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        # Add per-tenant unique constraint
        migrations.AddConstraint(
            model_name='paymentcategory',
            constraint=models.UniqueConstraint(
                fields=['tenant_id', 'name'],
                name='unique_payment_category_per_tenant',
            ),
        ),
    ]
