# Generated by Django 5.2.9 on 2026-06-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_billpayment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='billpayment',
            new_name='bill_paymen_tenant__d07334_idx',
            old_name='billpay_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='billpayment',
            new_name='bill_paymen_tenant__b5f95b_idx',
            old_name='billpay_tenant_type_idx',
        ),
        migrations.RenameIndex(
            model_name='billpayment',
            new_name='bill_paymen_tenant__fe48cc_idx',
            old_name='billpay_tenant_date_idx',
        ),
        migrations.RenameIndex(
            model_name='billpayment',
            new_name='bill_paymen_tenant__c0182f_idx',
            old_name='billpay_tenant_mode_idx',
        ),
        migrations.RenameIndex(
            model_name='billpayment',
            new_name='bill_paymen_opd_bil_1879e4_idx',
            old_name='billpay_opd_bill_idx',
        ),
        migrations.RenameIndex(
            model_name='billpayment',
            new_name='bill_paymen_ipd_bil_3aafb1_idx',
            old_name='billpay_ipd_bill_idx',
        ),
    ]
