# Generated by Django 5.2.9 on 2026-08-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0011_alter_ipdbilling_payment_mode'),
        ('opd', '0016_alter_opdbill_payment_mode'),
        ('payments', '0006_rename_bill_paymen_tenant__d07334_idx_billpay_tenant_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPaymentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('receipt_date', models.DateField(db_index=True)),
                ('prefix', models.CharField(max_length=30)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'bill_payment_sequences',
            },
        ),
        migrations.AddField(
            model_name='billpayment',
            name='payment_group_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups the rows recorded together as one payment event (e.g. a cash+online split) so they print as a single receipt.', null=True),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, help_text='Printable receipt number, auto-generated per tenant on first save.', max_length=40),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='bill_type',
            field=models.CharField(choices=[('opd', 'OPD'), ('ipd', 'IPD'), ('daycare', 'Daycare')], max_length=10),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('online', 'Online'), ('insurance', 'Insurance'), ('cheque', 'Cheque'), ('razorpay', 'Razorpay'), ('multiple', 'Multiple'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AddIndex(
            model_name='billpayment',
            index=models.Index(fields=['payment_group_id'], name='billpay_group_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='billpaymentsequence',
            unique_together={('tenant_id', 'receipt_date', 'prefix')},
        ),
    ]
