# Generated by Django 5.2.9 on 2026-08-19 07:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0013_admission_advance_applied_admission_advance_balance_and_more'),
        ('opd', '0016_alter_opdbill_payment_mode'),
        ('payments', '0007_billpaymentsequence_billpayment_payment_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='admission',
            field=models.ForeignKey(blank=True, help_text="Set only for bill_type='advance' rows: an unapplied (or partially applied) advance deposit for this admission.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_payments', to='ipd.admission'),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='applied_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="bill_type='advance' only: portion of this deposit already applied to a bill via apply_advance.", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='bill_type',
            field=models.CharField(choices=[('opd', 'OPD'), ('ipd', 'IPD'), ('daycare', 'Daycare'), ('advance', 'Advance')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='billpayment',
            index=models.Index(fields=['admission'], name='billpay_admission_idx'),
        ),
    ]
