# Generated by Django 5.2.9 on 2026-06-26 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantWebhook',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=1000)),
                ('secret', models.CharField(blank=True, default='', help_text='Shared secret for HMAC-SHA256 signature', max_length=255)),
                ('events', models.JSONField(default=list, help_text='List of event names to subscribe to; empty means all')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'tenant_webhooks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'is_active'], name='tenant_webh_tenant__bbb696_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('event_name', models.CharField(db_index=True, max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('response_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.tenantwebhook')),
            ],
            options={
                'db_table': 'webhook_deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='webhook_del_tenant__2f51ca_idx'), models.Index(fields=['tenant_id', 'webhook', '-created_at'], name='webhook_del_tenant__97348e_idx')],
            },
        ),
    ]
