# Generated by Django 5.2.9 on 2026-06-28 20:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorycategory',
            name='unique_inventory_category_code_per_tenant',
        ),
        migrations.RenameIndex(
            model_name='inventorybatch',
            new_name='inventory_b_tenant__2e01f9_idx',
            old_name='inv_batch_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorybatch',
            new_name='inventory_b_tenant__1dff3e_idx',
            old_name='inv_batch_tenant_item_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorybatch',
            new_name='inventory_b_tenant__535b2f_idx',
            old_name='inv_batch_tenant_expiry_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorybatch',
            new_name='inventory_b_item_id_84e77d_idx',
            old_name='inv_batch_item_expiry_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorycategory',
            new_name='inventory_c_tenant__ee3a25_idx',
            old_name='inv_cat_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorycategory',
            new_name='inventory_c_tenant__eb3093_idx',
            old_name='inv_cat_tenant_active_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='inventory_i_tenant__76240a_idx',
            old_name='inv_item_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='inventory_i_tenant__d6882d_idx',
            old_name='inv_item_tenant_active_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='inventory_i_tenant__046314_idx',
            old_name='inv_item_tenant_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='inventory_i_tenant__18140a_idx',
            old_name='inv_item_tenant_stock_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorysupplier',
            new_name='inventory_s_tenant__6ea311_idx',
            old_name='inv_sup_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorysupplier',
            new_name='inventory_s_tenant__1db421_idx',
            old_name='inv_sup_tenant_active_idx',
        ),
        migrations.RenameIndex(
            model_name='stockalert',
            new_name='inventory_a_tenant__9ca822_idx',
            old_name='inv_alert_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='stockalert',
            new_name='inventory_a_tenant__d48a2c_idx',
            old_name='inv_alert_tenant_active_idx',
        ),
        migrations.RenameIndex(
            model_name='stockalert',
            new_name='inventory_a_tenant__d934ab_idx',
            old_name='inv_alert_tenant_type_idx',
        ),
        migrations.RenameIndex(
            model_name='stockalert',
            new_name='inventory_a_tenant__f028f0_idx',
            old_name='inv_alert_tenant_ack_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransaction',
            new_name='inventory_t_tenant__11424e_idx',
            old_name='inv_txn_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransaction',
            new_name='inventory_t_tenant__3a97db_idx',
            old_name='inv_txn_tenant_item_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransaction',
            new_name='inventory_t_tenant__c58a13_idx',
            old_name='inv_txn_tenant_type_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransaction',
            new_name='inventory_t_tenant__261819_idx',
            old_name='inv_txn_tenant_date_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransaction',
            new_name='inventory_t_referen_ef9dcf_idx',
            old_name='inv_txn_ref_idx',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GST % (e.g. 12.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Always positive; direction inferred from transaction_type', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterUniqueTogether(
            name='inventorycategory',
            unique_together={('tenant_id', 'code')},
        ),
    ]
