# Generated by Django 5.2.9 on 2026-07-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventorycategory_unique_inventory_category_code_per_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycategory',
            name='expiry_alert_days',
            field=models.PositiveIntegerField(blank=True, help_text='Optional expiry-alert lead time for items in this category.', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='expiry_alert_days',
            field=models.PositiveIntegerField(blank=True, help_text='Optional item-specific expiry-alert lead time in days.', null=True),
        ),
    ]
