# Generated by Django 5.2.8 on 2025-12-21 19:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('patients', '0003_alter_patientprofile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenancy')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('base_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Therapy',
                'verbose_name_plural': 'Therapies',
                'db_table': 'pk_therapies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PanchakarmaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenancy')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the encounter record')),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('bill_item_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the bill item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_item_content_type', models.ForeignKey(blank=True, help_text='Type of bill item (OPDBillItem or IPDBillItem)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('content_type', models.ForeignKey(help_text='Type of encounter (OPD Visit or IPD Admission)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panchakarma_orders', to='patients.patientprofile')),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panchakarma.therapy')),
            ],
            options={
                'verbose_name': 'Panchakarma Order',
                'verbose_name_plural': 'Panchakarma Orders',
                'db_table': 'pk_orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PanchakarmaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenancy')),
                ('scheduled_date', models.DateTimeField()),
                ('session_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], default='scheduled', max_length=20)),
                ('therapist_id', models.UUIDField(blank=True, help_text='User ID of the therapist', null=True)),
                ('notes', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='panchakarma.panchakarmaorder')),
            ],
            options={
                'verbose_name': 'Panchakarma Session',
                'verbose_name_plural': 'Panchakarma Sessions',
                'db_table': 'pk_sessions',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.AddIndex(
            model_name='panchakarmaorder',
            index=models.Index(fields=['bill_item_content_type', 'bill_item_object_id'], name='pk_orders_bill_it_14ddeb_idx'),
        ),
    ]
