"""Centralized error codes for DigiHMS API responses.

All error codes use SCREAMING_SNAKE_CASE and are returned in the ``code``
field of :func:`common.responses.error_response`.
"""

# Generic / HTTP layer
UNAUTHORIZED = "UNAUTHORIZED"
FORBIDDEN = "FORBIDDEN"
NOT_FOUND = "NOT_FOUND"
METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
VALIDATION_ERROR = "VALIDATION_ERROR"
INVALID_PAYLOAD = "INVALID_PAYLOAD"
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"

# Auth / permission
JWT_MISSING = "JWT_MISSING"
JWT_INVALID = "JWT_INVALID"
JWT_EXPIRED = "JWT_EXPIRED"
JWT_MALFORMED = "JWT_MALFORMED"
PERMISSION_DENIED = "PERMISSION_DENIED"
MODULE_NOT_ENABLED = "MODULE_NOT_ENABLED"
TENANT_MISMATCH = "TENANT_MISMATCH"

# Database / concurrency
RECORD_NOT_FOUND = "RECORD_NOT_FOUND"
RECORD_ALREADY_EXISTS = "RECORD_ALREADY_EXISTS"
INTEGRITY_ERROR = "INTEGRITY_ERROR"
CONCURRENT_MODIFICATION = "CONCURRENT_MODIFICATION"

# Tenant isolation
TENANT_ID_REQUIRED = "TENANT_ID_REQUIRED"
TENANT_ID_MISMATCH = "TENANT_ID_MISMATCH"

# Clinical forms
FORM_NOT_FOUND = "FORM_NOT_FOUND"
FORM_NOT_PUBLISHED = "FORM_NOT_PUBLISHED"
FORM_VERSION_MISMATCH = "FORM_VERSION_MISMATCH"
AI_GENERATION_FAILED = "AI_GENERATION_FAILED"
INVALID_FORM_DRAFT = "INVALID_FORM_DRAFT"
DRAFT_ALREADY_APPLIED = "DRAFT_ALREADY_APPLIED"
SECTION_NOT_FOUND = "SECTION_NOT_FOUND"
FIELD_NOT_FOUND = "FIELD_NOT_FOUND"
FIELD_TYPE_INVALID = "FIELD_TYPE_INVALID"
PICKLIST_NOT_FOUND = "PICKLIST_NOT_FOUND"
PICKLIST_ITEM_NOT_FOUND = "PICKLIST_ITEM_NOT_FOUND"
RECORD_NOT_FOUND = "RECORD_NOT_FOUND"
RECORD_LOCKED = "RECORD_LOCKED"
RECORD_ALREADY_LOCKED = "RECORD_ALREADY_LOCKED"
SNAPSHOT_NOT_FOUND = "SNAPSHOT_NOT_FOUND"
PREFERENCE_NOT_FOUND = "PREFERENCE_NOT_FOUND"
INVALID_FIELD_VALUE = "INVALID_FIELD_VALUE"

# Webhooks
WEBHOOK_NOT_FOUND = "WEBHOOK_NOT_FOUND"
WEBHOOK_DELIVERY_FAILED = "WEBHOOK_DELIVERY_FAILED"
WEBHOOK_SIGNATURE_INVALID = "WEBHOOK_SIGNATURE_INVALID"
WEBHOOK_URL_INVALID = "WEBHOOK_URL_INVALID"

# Activity / health
HEALTH_CHECK_FAILED = "HEALTH_CHECK_FAILED"
