# Generated by Django 5.2.9 on 2025-12-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NakshatraLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name of the lead', max_length=100)),
                ('last_name', models.CharField(help_text='Last name of the lead', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the lead', max_length=255)),
                ('phone', models.CharField(help_text='Phone number of the lead', max_length=20)),
                ('services', models.CharField(help_text='Service type requested by the lead', max_length=255)),
                ('appointment_date', models.CharField(help_text='Appointment or inquiry date', max_length=100)),
                ('client_event_id', models.CharField(blank=True, help_text='Client-side event ID for Meta tracking deduplication', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the requester', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request', null=True)),
                ('custom_api_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('error', 'Error')], default='pending', help_text='Status of custom API submission', max_length=20)),
                ('custom_api_response', models.TextField(blank=True, help_text='Response from custom API', null=True)),
                ('meta_capi_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('error', 'Error')], default='pending', help_text='Status of Meta CAPI submission', max_length=20)),
                ('meta_capi_response', models.TextField(blank=True, help_text='Response from Meta CAPI', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the lead was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the lead was last updated')),
            ],
            options={
                'verbose_name': 'Nakshatra Lead',
                'verbose_name_plural': 'Nakshatra Leads',
                'db_table': 'nakshatra_leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='nakshatra_l_created_2469d1_idx'), models.Index(fields=['email'], name='nakshatra_l_email_e8f414_idx'), models.Index(fields=['phone'], name='nakshatra_l_phone_13100d_idx'), models.Index(fields=['custom_api_status'], name='nakshatra_l_custom__1d6132_idx'), models.Index(fields=['meta_capi_status'], name='nakshatra_l_meta_ca_f6c0db_idx')],
            },
        ),
    ]
