# Generated by Django 5.2.9 on 2026-08-05 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MrdExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_id', models.IntegerField(db_index=True)),
                ('requested_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('item_ids', models.JSONField(default=list)),
                ('export_format', models.CharField(default='pdf', max_length=8)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'patient_id', 'created_at'], name='mrd_mrdexpo_tenant__a904da_idx')],
            },
        ),
    ]
