# Generated by Django 5.2.9 on 2026-08-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrdexport',
            name='artifact_file',
            field=models.FileField(blank=True, null=True, upload_to='mrd_exports/'),
        ),
        migrations.AddField(
            model_name='mrdexport',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
