# Generated by Django 5.2.8 on 2025-11-16 17:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('user_id', models.UUIDField(help_text='User who owns this cart', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pharmacy_carts',
                'indexes': [models.Index(fields=['tenant_id'], name='pharmacy_ca_tenant__f656f5_idx'), models.Index(fields=['tenant_id', 'user_id'], name='pharmacy_ca_tenant__0c77d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='PharmacyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('user_id', models.UUIDField(blank=True, help_text='User who placed this order', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('shipping_address', models.TextField()),
                ('billing_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pharmacy_orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id'], name='pharmacy_or_tenant__c7bfcf_idx'), models.Index(fields=['tenant_id', 'status'], name='pharmacy_or_tenant__55cd8a_idx'), models.Index(fields=['tenant_id', 'user_id'], name='pharmacy_or_tenant__1cfcc2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('medicine', 'Medicine'), ('healthcare_product', 'Healthcare Product'), ('medical_equipment', 'Medical Equipment')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'db_table': 'pharmacy_product_categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant_id'], name='pharmacy_pr_tenant__0f1827_idx'), models.Index(fields=['tenant_id', 'name'], name='pharmacy_pr_tenant__cea6b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='PharmacyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('product_name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('minimum_stock_level', models.PositiveIntegerField(default=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pharmacy.productcategory')),
            ],
            options={
                'db_table': 'pharmacy_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('quantity', models.PositiveIntegerField()),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='pharmacy.pharmacyorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.pharmacyproduct')),
            ],
            options={
                'db_table': 'pharmacy_order_items',
                'indexes': [models.Index(fields=['tenant_id'], name='pharmacy_or_tenant__f4fb1c_idx'), models.Index(fields=['tenant_id', 'order'], name='pharmacy_or_tenant__ca7420_idx')],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='pharmacy.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacyproduct')),
            ],
            options={
                'db_table': 'pharmacy_cart_items',
                'indexes': [models.Index(fields=['tenant_id'], name='pharmacy_ca_tenant__ec6a05_idx'), models.Index(fields=['tenant_id', 'cart'], name='pharmacy_ca_tenant__99370c_idx')],
                'unique_together': {('cart', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='pharmacyproduct',
            index=models.Index(fields=['tenant_id'], name='pharmacy_pr_tenant__076853_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyproduct',
            index=models.Index(fields=['tenant_id', 'product_name'], name='pharmacy_pr_tenant__aca4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyproduct',
            index=models.Index(fields=['product_name'], name='pharmacy_pr_product_62c12c_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyproduct',
            index=models.Index(fields=['company'], name='pharmacy_pr_company_ba786f_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyproduct',
            index=models.Index(fields=['batch_no'], name='pharmacy_pr_batch_n_cfbf87_idx'),
        ),
    ]
