# Generated by Django 5.2.9 on 2025-12-23 20:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyproduct',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='pharmacyproduct',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='pharmacy_search_vector_idx'),
        ),
    ]
