# Generated by Django 5.2.9 on 2026-06-28 20:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventorycategory_unique_inventory_category_code_per_tenant_and_more'),
        ('opd', '0008_visit_priority_referral'),
        ('pharmacy', '0002_pharmacyproduct_search_vector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_dispensed', 'Partially Dispensed'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='General prescription notes')),
                ('created_by_user_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.ForeignKey(help_text='OPD visit this prescription belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='opd.visit')),
            ],
            options={
                'db_table': 'pharmacy_prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this record belongs to')),
                ('medicine_name', models.CharField(blank=True, help_text='Snapshot of inventory item name at prescription time', max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity prescribed', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('dispensed_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_dispensed', models.BooleanField(default=False)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('dispensed_by_user_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(help_text='Inventory item being prescribed', on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='inventory.inventoryitem')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescription')),
            ],
            options={
                'db_table': 'pharmacy_prescription_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['tenant_id'], name='pharmacy_pr_tenant__ca0aef_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['tenant_id', 'visit'], name='pharmacy_pr_tenant__ee0c13_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['tenant_id', 'status'], name='pharmacy_pr_tenant__34ac52_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['tenant_id'], name='pharmacy_pr_tenant__eafb3e_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['tenant_id', 'prescription'], name='pharmacy_pr_tenant__8a3b6e_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['tenant_id', 'inventory_item'], name='pharmacy_pr_tenant__58cd22_idx'),
        ),
    ]
