# Generated by Django 5.2.9 on 2026-06-28 22:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_prescriptionitem_inventory_item_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='instructions',
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quantity prescribed', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
