# Generated by Django 5.0.14 on 2025-11-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Consultation fee in INR', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='follow_up_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Follow-up consultation fee in INR', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
