# Generated by Django 5.0.14 on 2025-11-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctorprofile_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='medical_license_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
